# Generated by Django 5.0.1 on 2024-02-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obdrillingsummary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBDrillingProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obfgId', models.PositiveIntegerField()),
                ('obwellid', models.PositiveIntegerField()),
                ('obops_Date', models.DateField()),
                ('obhole_Size', models.CharField(choices=[('26_inch', '26_inch'), ('20_inch', '20_inch'), ('16_inch', '16_inch'), ('12_1/4_inch', '12_1/4_inch'), ('8_1/2_inch', '8_1/2_inch'), ('6_1/8_inch', '6_1/8_inch'), ('4_1/2_inch', '4_1/2_inch')], default='12_1/4_inch', max_length=50)),
                ('obdepth_From', models.FloatField()),
                ('obdepth_To', models.FloatField()),
                ('obdescription', models.TextField(max_length=2500)),
                ('obpossible_reason', models.TextField(max_length=2500)),
                ('obdrillingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obdrillingsummary.obdrillingsummary')),
            ],
        ),
    ]
