# Generated by Django 4.1 on 2023-05-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservoirfluidcomposition", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fluidcomposition",
            name="component",
        ),
        migrations.RemoveField(
            model_name="fluidcomposition",
            name="liquid_Density",
        ),
        migrations.RemoveField(
            model_name="fluidcomposition",
            name="mole_Percent",
        ),
        migrations.RemoveField(
            model_name="fluidcomposition",
            name="molecular_Weight",
        ),
        migrations.RemoveField(
            model_name="fluidcomposition",
            name="weight_Percent",
        ),
    ]
