# Generated by Django 4.1.4 on 2023-02-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrillingPlanVsActual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fgId", models.PositiveIntegerField()),
                ("wellid", models.PositiveIntegerField()),
                ("operation", models.TextField(max_length=100)),
                ("section_Depth_Plan", models.FloatField()),
                ("plan_Days", models.FloatField()),
                ("section_Depth_Actual", models.DateField()),
                ("actual_Days", models.FloatField()),
                ("reason_for_Deviation", models.TextField(max_length=2000)),
            ],
        ),
    ]
