# Generated by Django 4.1.4 on 2023-02-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drillingplanvsactual", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drillingplanvsactual",
            name="operation",
        ),
        migrations.AddField(
            model_name="drillingplanvsactual",
            name="section",
            field=models.TextField(
                choices=[
                    ("26_inch", "26_inch"),
                    ("23_inch", "23_inch"),
                    ("20_inch", "20_inch"),
                    ("17_1/2_inch", "17_1/2_inch"),
                    ("16_inch", "16_inch"),
                    ("12_1/4_inch", "12_1/4_inch"),
                    ("8_1/2_inch", "8_1/2_inch"),
                    ("6_1/8_inch", "6_1/8_inch"),
                    ("4_1/2_inch", "4_1/2_inch"),
                    ("Completion", "Completion"),
                    ("Logging", "Logging"),
                    ("Well_Test", "Well_Test"),
                ],
                default="26_inch",
                max_length=100,
            ),
        ),
    ]
