# Generated by Django 4.1.4 on 2023-02-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drillingplanvsactual", "0002_remove_drillingplanvsactual_operation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drillingplanvsactual",
            name="section_Depth_Actual",
            field=models.FloatField(),
        ),
    ]
