# Generated by Django 5.0.1 on 2024-02-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WIDrillingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifgId', models.PositiveIntegerField()),
                ('wiwellid', models.PositiveIntegerField()),
                ('wistart_Date', models.DateField()),
                ('wiend_Date', models.DateField()),
                ('wiliquid_Rate', models.FloatField()),
                ('wiwater_Cut', models.FloatField()),
                ('wigas_Rate', models.FloatField()),
                ('wioil_Rate', models.FloatField()),
                ('wigas_Oil_Ratio', models.FloatField()),
                ('widrilling_Summary', models.TextField(max_length=2000)),
            ],
        ),
    ]
