# Generated by Django 4.1 on 2023-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservoirfluidcompositiondata", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fluidcompositiondata",
            name="component",
            field=models.CharField(
                choices=[
                    ("Hydrogen_Sulfide", "Hydrogen_Sulfide"),
                    ("Carbon_Dioxide", "Carbon_Dioxide"),
                    ("Nitrogen", "Nitrogen"),
                    ("Methane", "Methane"),
                    ("Ethane", "Ethane"),
                    ("Propane", "Propane"),
                    ("iso-Butane", "iso-Butane"),
                    ("n-Butane", "n-Butane"),
                    ("iso-Pentane", "iso-Pentane"),
                    ("n-Pentane", "n-Pentane"),
                    ("Hexanes", "Hexanes"),
                    ("Heptanes", "Heptanes"),
                    ("Octanes", "Octanes"),
                    ("Nonanes", "Nonanes"),
                    ("Decanes", "Decanes"),
                    ("Undecanes", "Undecanes"),
                    ("Dodecanes", "Dodecanes"),
                    ("Tridecanes", "Tridecanes"),
                    ("Tetradecanes", "Tetradecanes"),
                    ("Pentadecanes", "Pentadecanes"),
                    ("Hexadecanes", "Hexadecanes"),
                    ("Heptadecanes", "Heptadecanes"),
                    ("Octadecanes", "Octadecanes"),
                    ("Nonadecanes", "Nonadecanes"),
                    ("Eicosanes", "Eicosanes"),
                    ("Heneicosanes", "Heneicosanes"),
                    ("Docosanes", "Docosanes"),
                    ("Tricosanes", "Tricosanes"),
                    ("Tetracosanes", "Tetracosanes"),
                    ("Pentacosanes", "Pentacosanes"),
                    ("Hexacosanes", "Hexacosanes"),
                    ("Heptacosanes", "Heptacosanes"),
                    ("Octacosanes", "Octacosanes"),
                    ("Nonacosanes", "Nonacosanes"),
                    ("Heptanes_plus", " Heptanes_plus"),
                    ("Undecanes_plus", "Undecanes_plus"),
                    ("Pentadecanes_plus", "Pentadecanes_plus"),
                    ("Eicosanes_plus", "Eicosanes_plus"),
                    ("Pentacosanes_plus", "Pentacosanes_plus"),
                    ("Triacontanes_plus ", "Triacontanes_plus "),
                ],
                default="Methane",
                max_length=100,
            ),
        ),
    ]
