# Generated by Django 4.0.5 on 2022-06-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedOilProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('wellid', models.PositiveIntegerField()),
                ('wellname', models.CharField(max_length=50)),
                ('completion', models.CharField(max_length=50)),
                ('deviation', models.CharField(max_length=50)),
                ('artificiallift', models.CharField(max_length=50)),
                ('inflow', models.CharField(max_length=50)),
                ('station', models.CharField(max_length=50)),
                ('header', models.CharField(max_length=50)),
            ],
        ),
    ]
