# Generated by Django 4.1 on 2023-05-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selectedOilProducer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="selectedoilproducer",
            name="category",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
