# Generated by Django 4.2.1 on 2023-05-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedLogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgId', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('survey_Date', models.DateField()),
                ('hole_size', models.CharField(max_length=50)),
                ('log_Type', models.CharField(max_length=50)),
                ('tool_string', models.CharField(max_length=100)),
                ('from_MD', models.FloatField()),
                ('to_MD', models.FloatField()),
                ('service_Provider', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
