# Generated by Django 4.2.1 on 2023-05-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordedlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedlogsmodel',
            name='hole_size',
            field=models.CharField(choices=[('26_inch', '26_inch'), ('20_inch', '20_inch'), ('16_inch', '16_inch'), ('12_1/4_inch', '12_1/4_inch'), ('8_1/2_inch', '8_1/2_inch'), ('6_1/8_inch', '6_1/8_inch'), ('4_1/2_inch', '4_1/2_inch')], default='12_1/4_inch', max_length=50),
        ),
        migrations.AlterField(
            model_name='recordedlogsmodel',
            name='log_Type',
            field=models.CharField(choices=[('LWD', 'LWD'), ('MWD', 'MWD'), ('Open_Hole', 'Open_Hole'), ('Cased_Hole', 'Cased_Hole')], default='Open_Hole', max_length=50),
        ),
    ]
