# Generated by Django 4.2.1 on 2023-05-27 00:56

from django.db import migrations, models
import recordedlogs.models


class Migration(migrations.Migration):

    dependencies = [
        ('recordedlogs', '0002_alter_recordedlogsmodel_hole_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedlogsmodel',
            name='analyst',
            field=models.CharField(default='Santhana', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordedlogsmodel',
            name='file_Name',
            field=models.FileField(blank=True, null=True, upload_to=recordedlogs.models.filepath),
        ),
        migrations.AddField(
            model_name='recordedlogsmodel',
            name='file_type',
            field=models.CharField(choices=[('LAS', 'LAS'), ('CSV', 'CSV'), ('DLIS', 'DLIS')], default='LAS', max_length=50),
        ),
        migrations.AddField(
            model_name='recordedlogsmodel',
            name='interpretation',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordedlogsmodel',
            name='logImage',
            field=models.ImageField(blank=True, null=True, upload_to=recordedlogs.models.filepath),
        ),
    ]
