# Generated by Django 4.2.1 on 2023-06-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordedlogs', '0003_recordedlogsmodel_analyst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedlogsmodel',
            name='analyst',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='recordedlogsmodel',
            name='service_Provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recordedlogsmodel',
            name='unit_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
