# Generated by Django 4.1 on 2023-05-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("constantcompositionexpansiondata", "0002_alter_ccepvtdata_y_function"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ccepvtdata",
            name="density",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
