# Generated by Django 3.0.14 on 2022-05-11 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sublayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublayername', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('area', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.Layer')),
            ],
        ),
    ]
