# Generated by Django 4.2.1 on 2023-06-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasLiftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgId', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('design_Date', models.DateField()),
                ('design_Liquid', models.FloatField()),
                ('water_Cut', models.FloatField()),
                ('th_Pres', models.FloatField()),
                ('th_Temp', models.FloatField()),
                ('gas_Inj_Pres', models.FloatField()),
                ('available_Gas', models.FloatField()),
                ('kick_Off_Pres', models.FloatField()),
                ('kill_Fluid_Grad', models.FloatField()),
                ('port_Size', models.FloatField()),
                ('min_Valve_Sapcing', models.FloatField()),
            ],
        ),
    ]
