# Generated by Django 5.0.1 on 2024-02-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obcasings', '0001_initial'),
        ('obleakoffTests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBLeakoffTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtime', models.FloatField()),
                ('obvolume', models.FloatField()),
                ('obpressure', models.FloatField()),
                ('obcasingSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obcasings.obcasingsizemodel')),
                ('obleakoffTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obleakoffTests.obleakofftest')),
            ],
        ),
    ]
