# Generated by Django 5.0.1 on 2024-02-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GIDeviationsurveydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifgId', models.PositiveIntegerField()),
                ('giwellid', models.PositiveIntegerField()),
                ('gimeasuredDepth', models.FloatField()),
                ('giangle', models.FloatField()),
                ('giazimuth', models.FloatField()),
                ('gitvd', models.FloatField(blank=True, null=True)),
                ('ginorthSouth', models.FloatField(blank=True, null=True)),
                ('gieastWest', models.FloatField(blank=True, null=True)),
                ('ginetDrift', models.FloatField(blank=True, null=True)),
                ('ginetDirection', models.FloatField(blank=True, null=True)),
                ('giverticalSection', models.FloatField(blank=True, null=True)),
                ('gidogLeg', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
