# Generated by Django 3.0.14 on 2022-05-17 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selectedfgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitid', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('selectedassetname', models.CharField(max_length=200)),
                ('selectedblockname', models.CharField(max_length=200)),
                ('selectedfieldname', models.CharField(max_length=200)),
                ('selectedlayername', models.CharField(max_length=200)),
                ('selectedsublayername', models.CharField(max_length=200)),
            ],
        ),
    ]
