# Generated by Django 3.0.14 on 2022-05-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selectedfgi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedfgi',
            name='unitid',
        ),
        migrations.AlterModelTable(
            name='selectedfgi',
            table='Selectedfgi',
        ),
    ]
