# Generated by Django 3.0.14 on 2022-05-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectedfgi', '0002_auto_20220519_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedfgi',
            name='FGid',
            field=models.IntegerField(default=1, max_length=1000),
        ),
        migrations.AlterModelTable(
            name='selectedfgi',
            table=None,
        ),
    ]
