# Generated by Django 3.0.14 on 2022-05-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectedfgi', '0003_auto_20220520_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedfgi',
            name='FGid',
            field=models.IntegerField(default=1),
        ),
    ]
