# Generated by Django 4.1 on 2023-04-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selectedfgi", "0005_remove_selectedfgi_fgid_selectedfgi_fgid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selectedfgi",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
