# Generated by Django 5.0.1 on 2024-02-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPCementPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpwellid', models.PositiveBigIntegerField()),
                ('gpfgid', models.PositiveBigIntegerField()),
                ('gpplug_Date', models.DateField()),
                ('gpplug_Top', models.FloatField()),
                ('gpplug_Bottom', models.FloatField()),
                ('gpcement_Density', models.FloatField()),
                ('gpcement_Volume', models.FloatField()),
                ('gpplug_Description', models.TextField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPPumpingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpwellid', models.PositiveBigIntegerField()),
                ('gpfgid', models.PositiveBigIntegerField()),
                ('gppump_Time', models.TimeField()),
                ('gppump_Fluid', models.CharField(blank=True, choices=[('Pre_Flush', 'Pre_Flush'), ('Slurry', 'Slurry'), ('Post_Flush', 'Post_Flush'), ('Water', 'Water')], default='Pre_Flush', max_length=20, null=True)),
                ('gppump_Fluid_Density', models.FloatField()),
                ('gppump_Pressure', models.FloatField()),
                ('gppump_Rate', models.FloatField()),
                ('gpcementplug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpcementplugs.gpcementplug')),
            ],
        ),
    ]
