# Generated by Django 4.1.4 on 2023-02-28 05:54

from django.db import migrations, models
import layers.models


class Migration(migrations.Migration):

    dependencies = [
        ("layers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="volumetric_data",
            field=models.FileField(
                blank=True, null=True, upload_to=layers.models.filepath
            ),
        ),
    ]
