# Generated by Django 4.0.5 on 2022-10-18 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blackoilpvt', '0018_alter_blackoilpvt_pbcorrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressureBuildupDataUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_Date', models.DateField()),
                ('time', models.TimeField()),
                ('gauge_pressure', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PressureBuildupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('survey_Date', models.DateField()),
                ('gauge_Depth', models.FloatField()),
                ('layer_Thickness', models.FloatField()),
                ('layer_Porosity', models.FloatField()),
                ('total_Compressibility', models.FloatField()),
                ('well_spacing', models.FloatField()),
                ('wellbore_Radius', models.FloatField()),
                ('liquid_Prod_Rate', models.FloatField()),
                ('water_Cut', models.FloatField()),
                ('dataFile', models.FileField(blank=True, null=True, upload_to='uploads/PBUData/')),
                ('pvt_Well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackoilpvt.blackoilpvt')),
            ],
        ),
    ]
