# Generated by Django 4.0.5 on 2022-10-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressurebuildupanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressurebuildupdatauploadmodel',
            name='elapsedtime',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
