# Generated by Django 5.0.1 on 2024-02-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GIReservoirPressureEstimationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifgid', models.PositiveIntegerField()),
                ('giwellid', models.PositiveIntegerField()),
                ('gianalysis_Date', models.DateField()),
                ('gilayer_Permeability', models.FloatField()),
                ('gilayer_Thickness', models.FloatField()),
                ('gilayer_Porosity', models.FloatField()),
                ('gitotal_Compressibility', models.FloatField()),
                ('gimu_oil', models.FloatField()),
                ('gioil_FVF', models.FloatField()),
                ('giwellbore_Radius', models.FloatField()),
                ('gioil_Prod_Rate', models.FloatField()),
                ('giini_Res_Pres', models.FloatField()),
                ('gidrainage_Radius', models.FloatField()),
            ],
        ),
    ]
