# Generated by Django 5.0.1 on 2024-02-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPCasingGradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpcasingGrade', models.CharField(max_length=20)),
                ('gpcollapsePressure', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gpburstPressure', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GPCasingSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpcasingSize', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GPCasingWeightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpcasingWeight', models.CharField(max_length=20)),
                ('gpcasingID', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gpcasingSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpcasings.gpcasingsizemodel')),
            ],
        ),
        migrations.CreateModel(
            name='GPCasingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgid', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpcasingType', models.CharField(blank=True, choices=[('Surface', 'Surface'), ('Conductor', 'Conductor'), ('Internediate_1', 'Internediate1'), ('Intermediate_2', 'Intermediate2'), ('Intermediate_3', 'Intermediate2'), ('Liner_casing', 'Linercasing'), ('Production_Casing', 'ProductionCasing'), ('Production_Liner', 'ProductionLiner')], default='Surface', max_length=20, null=True)),
                ('gpcasingID', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('gpcollapsePressure', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('gpburstPressure', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('gpthreadType', models.CharField(blank=True, choices=[('1', 'STC'), ('2', 'LTC'), ('3', 'BTC'), ('4', 'LP'), ('5', 'EUE'), ('6', 'NUE'), ('7', 'IJ'), ('8', 'VAM'), ('9', 'NEWVAM')], default='1', max_length=20, null=True)),
                ('gpmaterial', models.CharField(blank=True, choices=[('1', 'Carbon_Steel'), ('2', 'CRA_9Cr'), ('3', 'CRA_13Cr'), ('4', 'Inconel')], default='1', max_length=20, null=True)),
                ('gpshoedepth', models.FloatField()),
                ('gpfloatCollar', models.FloatField()),
                ('gphangerDepth', models.FloatField()),
                ('gpcementTop', models.FloatField()),
                ('gpcasingGrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casingGrades', to='gpcasings.gpcasinggrademodel')),
                ('gpcasingSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casingSizes', to='gpcasings.gpcasingsizemodel')),
                ('gpcasingWeight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casingWeights', to='gpcasings.gpcasingweightmodel')),
            ],
        ),
        migrations.AddField(
            model_name='gpcasinggrademodel',
            name='gpcasingWeight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpcasings.gpcasingweightmodel'),
        ),
    ]
