# Generated by Django 4.2.1 on 2023-05-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerforationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('perf_Date', models.DateField()),
                ('perf_Top', models.FloatField()),
                ('perf_Bottom', models.FloatField()),
                ('perf_Condition', models.CharField(choices=[('Over_Balanced', 'Over_Balanced'), ('Under_balanced', 'Under_balanced')], default='Over_Balanced', max_length=50)),
                ('conveyance_Method', models.CharField(choices=[('Through_Casing', 'Through_Casing'), ('Through_Tubing', 'Through_Tubing'), ('TCP', 'TCP')], default='Retrievable_Hallow', max_length=50)),
                ('perf_Gun_Type', models.CharField(choices=[('Retrievable_Hallow', 'Retrievable_Hallow'), ('Expendable', 'Expendable'), ('Semi_Expendable', 'Semi_Expendable')], default='Retrievable_Hallow', max_length=50)),
                ('perf_Gun_Size', models.CharField(choices=[('2_in', '2_in'), ('2_3/4_In', '2_3/4_in'), ('3_1/8_in', '3_1/8_in'), ('3_3/8_in', '3_3/8_in')], default='2_in', max_length=50)),
                ('perf_Gun_Density', models.CharField(max_length=50)),
                ('perf_Charges', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
