# Generated by Django 5.0.1 on 2024-02-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPDeviationsurveydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgId', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpmeasuredDepth', models.FloatField()),
                ('gpangle', models.FloatField()),
                ('gpazimuth', models.FloatField()),
                ('gptvd', models.FloatField(blank=True, null=True)),
                ('gpnorthSouth', models.FloatField(blank=True, null=True)),
                ('gpeastWest', models.FloatField(blank=True, null=True)),
                ('gpnetDrift', models.FloatField(blank=True, null=True)),
                ('gpnetDirection', models.FloatField(blank=True, null=True)),
                ('gpverticalSection', models.FloatField(blank=True, null=True)),
                ('gpdogLeg', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
