# Generated by Django 5.0.1 on 2024-02-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBReservoirPressureEstimationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obfgid', models.PositiveIntegerField()),
                ('obwellid', models.PositiveIntegerField()),
                ('obanalysis_Date', models.DateField()),
                ('oblayer_Permeability', models.FloatField()),
                ('oblayer_Thickness', models.FloatField()),
                ('oblayer_Porosity', models.FloatField()),
                ('obtotal_Compressibility', models.FloatField()),
                ('obmu_oil', models.FloatField()),
                ('oboil_FVF', models.FloatField()),
                ('obwellbore_Radius', models.FloatField()),
                ('oboil_Prod_Rate', models.FloatField()),
                ('obini_Res_Pres', models.FloatField()),
                ('obdrainage_Radius', models.FloatField()),
            ],
        ),
    ]
