# Generated by Django 4.1.4 on 2023-02-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrillingSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fgId", models.PositiveIntegerField()),
                ("wellid", models.PositiveIntegerField()),
                ("start_Date", models.DateField()),
                ("end_Date", models.DateField()),
                ("liquid_Rate", models.FloatField()),
                ("water_Cut", models.FloatField()),
                ("gas_Rate", models.FloatField()),
                ("oil_Rate", models.FloatField()),
                ("gas_Oil_Ratio", models.FloatField()),
                ("drilling_Summary", models.TextField(max_length=2000)),
            ],
        ),
    ]
