# Generated by Django 5.0.1 on 2024-02-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WITestResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witest_DurationfgId', models.PositiveIntegerField()),
                ('witest_Durationwellid', models.PositiveIntegerField()),
                ('witest_Durationformation', models.CharField(max_length=100)),
                ('witest_Durationtop_MD', models.FloatField()),
                ('witest_Durationbottom_MD', models.FloatField()),
                ('witest_Durationtest_Duration', models.FloatField()),
                ('witest_Durationchoke_Size', models.CharField(max_length=100)),
                ('witest_Durationthp', models.FloatField()),
                ('witest_Durationbhp', models.FloatField()),
                ('witest_Durationliquid_Rate', models.FloatField()),
                ('witest_Durationoil_Rate', models.FloatField()),
                ('witest_Durationgas_Rate', models.FloatField()),
                ('witest_Durationwater_Cut', models.FloatField()),
                ('witest_Durationremarks', models.CharField(max_length=100)),
            ],
        ),
    ]
