# Generated by Django 5.0.1 on 2024-02-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('witestresults', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_Durationbhp',
            new_name='wibhp',
        ),
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_Durationbottom_MD',
            new_name='wibottom_MD',
        ),
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_Durationchoke_Size',
            new_name='wichoke_Size',
        ),
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_DurationfgId',
            new_name='wifgId',
        ),
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_Durationformation',
            new_name='wiformation',
        ),
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_Durationgas_Rate',
            new_name='wigas_Rate',
        ),
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_Durationliquid_Rate',
            new_name='wiliquid_Rate',
        ),
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_Durationoil_Rate',
            new_name='wioil_Rate',
        ),
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_Durationremarks',
            new_name='wiremarks',
        ),
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_Durationtest_Duration',
            new_name='witest_Duration',
        ),
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_Durationthp',
            new_name='withp',
        ),
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_Durationtop_MD',
            new_name='witop_MD',
        ),
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_Durationwater_Cut',
            new_name='wiwater_Cut',
        ),
        migrations.RenameField(
            model_name='witestresultmodel',
            old_name='witest_Durationwellid',
            new_name='wiwellid',
        ),
    ]
