# Generated by Django 5.0.1 on 2024-02-16 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gigradientsurveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GIGradientSurveyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giwellid', models.PositiveIntegerField()),
                ('gigauge_Depth', models.FloatField()),
                ('gigauge_Pressure', models.FloatField()),
                ('gigauge_Temperature', models.FloatField()),
                ('gigradientsurvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigradientsurveys.gigradientsurvey')),
            ],
        ),
    ]
