# Generated by Django 4.2.1 on 2023-05-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgId', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('hole_Size', models.CharField(choices=[('18 1/2', '18 1/2'), ('17 1/2', '17 1/2'), ('15', '15'), ('14 3/4', '14 3/4'), ('12 1/4', '12 1/4'), ('12', '12'), ('10 5/8', '10 5/8'), ('9 7/8', '9 7/8'), ('9 5/8', '9 5/8'), ('9 1/2', '9 1/2'), ('8 3/4', '8 3/4'), ('8 5/8', '8 5/8'), ('8 1/2', '8 1/2'), ('8 3/8', '8 3/8'), ('7 7/8', '7 7/8'), ('7 5/8', '7 5/8'), ('6 3/4', '6 3/4'), ('6 5/8', '6 5/8'), ('6 1/4', '6 1/4'), ('6 1/8', '6 1/8'), ('6', '6'), ('5 7/8', '5 7/8'), ('5 5/8', '5 5/8'), ('4 3/4', '4 3/4'), ('4 5/8', '4 5/8'), ('4 1/2', '4 1/2'), ('4 1/4', '4 1/4'), ('4 1/8', '4 1/8'), ('3 7/8', '3 7/8'), ('3 3/4', '3 3/4')], default='8 1/2', max_length=20)),
                ('top_Depth', models.FloatField()),
                ('bottom_Depth', models.FloatField()),
                ('litho_1', models.CharField(max_length=100)),
                ('litho1_Composition', models.FloatField()),
                ('litho_2', models.CharField(max_length=100)),
                ('litho2_Composition', models.FloatField()),
                ('litho_3', models.CharField(max_length=100)),
                ('litho3_Composition', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
