# Generated by Django 4.1 on 2023-04-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0002_alter_block_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
