# Generated by Django 5.0.1 on 2024-02-19 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obcoiltubing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBCoiltubingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obfgid', models.PositiveIntegerField()),
                ('obwellid', models.PositiveIntegerField()),
                ('obctname', models.CharField(max_length=50)),
                ('obop_Date', models.DateField()),
                ('obtime_from', models.TimeField()),
                ('obtime_to', models.TimeField()),
                ('obtotalhrs', models.FloatField()),
                ('obop_code', models.CharField(choices=[('None', 'None'), ('Operating', 'Operating'), ('Standby', 'Standby'), ('Mobilization', 'Mobilization'), ('Demobilization', 'Demobilization'), ('WaitingonEquipment', 'WaitingonEquipment'), ('NonProductive', 'NonProductive')], default='Operating', max_length=50)),
                ('obop_details', models.CharField(max_length=150)),
                ('obcoiltubingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obcoiltubing.obcoiltubing')),
            ],
        ),
    ]
