# Generated by Django 5.0.1 on 2024-02-09 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GICementPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giwellid', models.PositiveBigIntegerField()),
                ('gifgid', models.PositiveBigIntegerField()),
                ('giplug_Date', models.DateField()),
                ('giplug_Top', models.FloatField()),
                ('giplug_Bottom', models.FloatField()),
                ('gicement_Density', models.FloatField()),
                ('gicement_Volume', models.FloatField()),
                ('giplug_Description', models.TextField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GIPumpingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giwellid', models.PositiveBigIntegerField()),
                ('gifgid', models.PositiveBigIntegerField()),
                ('gipump_Time', models.TimeField()),
                ('gipump_Fluid', models.CharField(blank=True, choices=[('Pre_Flush', 'Pre_Flush'), ('Slurry', 'Slurry'), ('Post_Flush', 'Post_Flush'), ('Water', 'Water')], default='Pre_Flush', max_length=20, null=True)),
                ('gipump_Fluid_Density', models.FloatField()),
                ('gipump_Pressure', models.FloatField()),
                ('gipump_Rate', models.FloatField()),
                ('gicementplug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gicementplugs.gicementplug')),
            ],
        ),
    ]
