# Generated by Django 5.0.1 on 2024-02-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBDrillingWellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obfgId', models.PositiveIntegerField()),
                ('obwellid', models.PositiveIntegerField()),
                ('obsurvey_Date', models.DateField()),
                ('obrkb_to_WH', models.FloatField()),
                ('obrkb_to_GL', models.FloatField()),
                ('obgl_to_MSL', models.FloatField()),
                ('obrkb_to_MSL', models.FloatField()),
                ('obwh_to_MSL', models.FloatField()),
                ('oblattitude', models.CharField(max_length=20)),
                ('oblongitude', models.CharField(max_length=20)),
                ('obtotal_Measured_Depth', models.FloatField()),
                ('obtotal_True_Vertical_Depth', models.FloatField()),
                ('obafe_No', models.CharField(max_length=40)),
            ],
        ),
    ]
