# Generated by Django 5.0.1 on 2024-02-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WIFormatioPressureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifgId', models.PositiveIntegerField()),
                ('wiwellid', models.PositiveIntegerField()),
                ('wistat_Group', models.CharField(max_length=100)),
                ('wistat_Formation', models.CharField(max_length=100)),
                ('wistat_Member', models.CharField(max_length=100)),
                ('wimeasured_Depth', models.FloatField()),
                ('wipressure', models.FloatField()),
                ('wiporosity', models.FloatField()),
                ('wipermeability', models.FloatField()),
                ('witemperature', models.FloatField()),
                ('wiremarks', models.CharField(max_length=100)),
            ],
        ),
    ]
