# Generated by Django 5.0.1 on 2024-02-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBGasShowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obfgId', models.PositiveIntegerField()),
                ('obwellid', models.PositiveIntegerField()),
                ('obformation', models.CharField(max_length=100)),
                ('obtop_MD', models.FloatField()),
                ('obbottom_MD', models.FloatField()),
                ('obtotal_Gas', models.FloatField()),
                ('obmethane', models.FloatField()),
                ('obethane', models.FloatField()),
                ('obpropane', models.FloatField()),
                ('obiso_Butane', models.FloatField()),
                ('obneo_Butane', models.FloatField()),
                ('obiso_Pentane', models.FloatField()),
                ('obneo_Pentane', models.FloatField()),
                ('obremarks', models.CharField(max_length=100)),
            ],
        ),
    ]
