# Generated by Django 4.2.1 on 2023-07-15 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blackoilpvt', '0019_alter_blackoilpvt_gasgravity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JetPumpDesignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('design_Date', models.DateField()),
                ('design_Liquid', models.FloatField()),
                ('water_Cut', models.FloatField()),
                ('water_Spgr', models.FloatField()),
                ('th_Pres', models.FloatField()),
                ('th_Temp', models.FloatField()),
                ('curr_Res_Pres', models.FloatField()),
                ('min_Pwf', models.FloatField()),
                ('gas_Oil_Ratio', models.FloatField()),
                ('pump_depth', models.FloatField()),
                ('pvt_Well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blackoilpvt.blackoilpvt')),
            ],
        ),
    ]
