# Generated by Django 4.1 on 2023-05-02 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sublayers", "0003_alter_sublayer_area_alter_sublayer_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CCEPVT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fgId", models.PositiveIntegerField()),
                ("wellName", models.CharField(max_length=100)),
                ("sampleId", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("temperature", models.FloatField()),
                (
                    "subLayer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sublayers.sublayer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CCEPVTData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pressure", models.FloatField()),
                ("relative_volume", models.FloatField()),
                ("y_function", models.FloatField()),
                ("density", models.FloatField()),
                (
                    "ccepvt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="constantcompositionexpansion.ccepvt",
                    ),
                ),
            ],
        ),
    ]
