# Generated by Django 4.1 on 2023-05-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("constantcompositionexpansion", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CCEPVTData",
        ),
    ]
