# Generated by Django 3.0.14 on 2022-06-05 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opwellobjectives', '0002_delete_opwellobjectivedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPWellobjectivedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('liquidrate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('watercut', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gasoilratio', models.DecimalField(decimal_places=3, max_digits=10)),
                ('opwellobjectiveid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opwellobjectives.OPWellobjective')),
            ],
        ),
    ]
