# Generated by Django 4.0.5 on 2022-07-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opwellobjectivedata', '0002_remove_opwellobjectivedata_opwellobjectiveid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opwellobjectivedata',
            name='gasrate',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opwellobjectivedata',
            name='oilrate',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opwellobjectivedata',
            name='waterrate',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
