# Generated by Django 4.1 on 2023-04-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opwellobjectivedata", "0004_alter_opwellobjectivedata_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opwellobjectivedata",
            name="gasoilratio",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="opwellobjectivedata",
            name="gasrate",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="opwellobjectivedata",
            name="liquidrate",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="opwellobjectivedata",
            name="oilrate",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="opwellobjectivedata",
            name="watercut",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="opwellobjectivedata",
            name="waterrate",
            field=models.FloatField(),
        ),
    ]
