# Generated by Django 4.1 on 2023-05-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("opwellobjectives", "0005_alter_opwellobjective_id"),
        ("opwellobjectivedata", "0005_alter_opwellobjectivedata_gasoilratio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opwellobjectivedata",
            name="opwellobjective",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="opwellobjectives.opwellobjective",
            ),
            preserve_default=False,
        ),
    ]
