# Generated by Django 4.2.1 on 2023-05-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opwellobjectivedata', '0006_opwellobjectivedata_opwellobjective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opwellobjectivedata',
            name='gasrate',
        ),
        migrations.RemoveField(
            model_name='opwellobjectivedata',
            name='oilrate',
        ),
        migrations.RemoveField(
            model_name='opwellobjectivedata',
            name='waterrate',
        ),
        migrations.AlterField(
            model_name='opwellobjectivedata',
            name='gasoilratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
