# Generated by Django 5.0.1 on 2024-02-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GIFormatioPressureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifgId', models.PositiveIntegerField()),
                ('giwellid', models.PositiveIntegerField()),
                ('gistat_Group', models.CharField(max_length=100)),
                ('gistat_Formation', models.CharField(max_length=100)),
                ('gistat_Member', models.CharField(max_length=100)),
                ('gimeasured_Depth', models.FloatField()),
                ('gipressure', models.FloatField()),
                ('giporosity', models.FloatField()),
                ('gipermeability', models.FloatField()),
                ('gitemperature', models.FloatField()),
                ('giremarks', models.CharField(max_length=100)),
            ],
        ),
    ]
