# Generated by Django 4.2.1 on 2023-05-26 05:38

from django.db import migrations, models
import multiratedrawdowntestanalysis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiRateDrawdowntest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('survey_Date', models.DateField()),
                ('gauge_Depth', models.FloatField()),
                ('layer_Porosity', models.FloatField()),
                ('layer_Thickness', models.FloatField()),
                ('wellbore_Radius', models.FloatField()),
                ('total_Compressibility', models.FloatField()),
                ('initial_Res_Pres', models.FloatField()),
                ('oil_Viscosity', models.FloatField()),
                ('oil_FVF', models.FloatField()),
                ('file_Name', models.FileField(blank=True, null=True, upload_to=multiratedrawdowntestanalysis.models.filepath)),
            ],
        ),
    ]
