# Generated by Django 4.2.1 on 2023-05-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiratedrawdowntestanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiratedrawdowntest',
            name='pressure1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiratedrawdowntest',
            name='pressure2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiratedrawdowntest',
            name='pressure3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiratedrawdowntest',
            name='time1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiratedrawdowntest',
            name='time2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiratedrawdowntest',
            name='time3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
