# Generated by Django 5.0.1 on 2024-03-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiratedrawdowntestanalysis', '0003_rename_file_name_multiratedrawdowntest_file_name_csv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiratedrawdowntest',
            old_name='pressure1',
            new_name='rate1',
        ),
        migrations.RenameField(
            model_name='multiratedrawdowntest',
            old_name='pressure2',
            new_name='rate2',
        ),
        migrations.RenameField(
            model_name='multiratedrawdowntest',
            old_name='pressure3',
            new_name='rate3',
        ),
    ]
