# Generated by Django 5.0.1 on 2024-02-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gioilshows', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OBOilShowModel',
            new_name='GIOilShowModel',
        ),
    ]
