# Generated by Django 4.0.5 on 2022-06-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrillingWellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgId', models.PositiveIntegerField()),
                ('wellName', models.CharField(max_length=20)),
                ('survey_date', models.DateField()),
                ('rkbtowh', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rkbtogl', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gltomsl', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rkbtomsl', models.DecimalField(decimal_places=3, max_digits=10)),
                ('whtomsl', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lattitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('measureddepth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('trueverticaldepth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('afeno', models.CharField(max_length=40)),
            ],
        ),
    ]
