# Generated by Django 4.1.4 on 2023-02-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drillingwelldata", "0003_remove_drillingwelldata_wellname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drillingwelldata",
            name="gltomsl",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="drillingwelldata",
            name="measureddepth",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="drillingwelldata",
            name="rkbtogl",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="drillingwelldata",
            name="rkbtomsl",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="drillingwelldata",
            name="rkbtowh",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="drillingwelldata",
            name="trueverticaldepth",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="drillingwelldata",
            name="whtomsl",
            field=models.FloatField(),
        ),
    ]
