# Generated by Django 4.2.1 on 2023-05-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drillingwelldata', '0004_alter_drillingwelldata_gltomsl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drillingwelldata',
            old_name='afeno',
            new_name='afe_No',
        ),
        migrations.RenameField(
            model_name='drillingwelldata',
            old_name='gltomsl',
            new_name='gl_to_MSL',
        ),
        migrations.RenameField(
            model_name='drillingwelldata',
            old_name='measureddepth',
            new_name='rkb_to_GL',
        ),
        migrations.RenameField(
            model_name='drillingwelldata',
            old_name='rkbtogl',
            new_name='rkb_to_MSL',
        ),
        migrations.RenameField(
            model_name='drillingwelldata',
            old_name='rkbtomsl',
            new_name='rkb_to_WH',
        ),
        migrations.RenameField(
            model_name='drillingwelldata',
            old_name='survey_date',
            new_name='survey_Date',
        ),
        migrations.RenameField(
            model_name='drillingwelldata',
            old_name='rkbtowh',
            new_name='total_Measured_Depth',
        ),
        migrations.RenameField(
            model_name='drillingwelldata',
            old_name='trueverticaldepth',
            new_name='total_True_Vertical_Depth',
        ),
        migrations.RenameField(
            model_name='drillingwelldata',
            old_name='whtomsl',
            new_name='wh_to_MSL',
        ),
    ]
