# Generated by Django 4.2.1 on 2023-05-10 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sublayers', '0003_alter_sublayer_area_alter_sublayer_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterAnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgId', models.PositiveIntegerField()),
                ('wellName', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('sampleId', models.PositiveIntegerField()),
                ('samplepoint', models.CharField(choices=[('Wellhead', 'Wellhead'), ('Flowline', 'Flowline'), ('Separator', 'Separator')], default='Wellhead', max_length=50)),
                ('lab', models.CharField(max_length=100)),
                ('sodium', models.FloatField()),
                ('calcium', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('pottasium', models.FloatField()),
                ('ferric', models.FloatField()),
                ('bicarbonate', models.FloatField()),
                ('sulphate', models.FloatField()),
                ('chloride', models.FloatField()),
                ('nitrate', models.FloatField()),
                ('tds', models.FloatField()),
                ('temperature', models.FloatField()),
                ('ph', models.FloatField()),
                ('subLayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sublayers.sublayer')),
            ],
        ),
    ]
