# Generated by Django 5.0.1 on 2024-02-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wateranalysis', '0002_wateranalysismodel_carbonate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wateranalysismodel',
            name='sodium',
            field=models.FloatField(null=True),
        ),
    ]
