# Generated by Django 5.0.1 on 2024-02-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GIDrillingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifgId', models.PositiveIntegerField()),
                ('giwellid', models.PositiveIntegerField()),
                ('gistart_Date', models.DateField()),
                ('giend_Date', models.DateField()),
                ('giliquid_Rate', models.FloatField()),
                ('giwater_Cut', models.FloatField()),
                ('gigas_Rate', models.FloatField()),
                ('gioil_Rate', models.FloatField()),
                ('gigas_Oil_Ratio', models.FloatField()),
                ('gidrilling_Summary', models.TextField(max_length=2000)),
            ],
        ),
    ]
