# Generated by Django 4.1.4 on 2023-02-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Completion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fgid", models.PositiveIntegerField()),
                ("wellid", models.PositiveIntegerField()),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("Tubing", "Tubing"),
                            ("PupJoint", "PupJoint"),
                            ("FlowCoupling", "FlowCoupling"),
                            ("SSD", "SSD"),
                            ("WEG", "WEG"),
                            ("SCSSSV", "SCSSSV"),
                            ("TCPGuns", "TCPGuns"),
                            ("Packer", "Packer"),
                            ("LandingNipple", "LandingNipple"),
                            ("BlastJoint", "BlastJoint"),
                            ("PerforatedPupJoint", "PerforatedPupJoint"),
                            ("Tubing_end", "Tubing_end"),
                            ("PlugbackDepth", "PlugbackDepth"),
                            ("Hold_up_Depth", "Hold_up_Depth"),
                        ],
                        default="Single",
                        max_length=50,
                    ),
                ),
                ("equip_Od", models.FloatField()),
                ("equip_Id", models.FloatField()),
                ("equip_Md", models.FloatField()),
                ("equip_Tvd", models.FloatField()),
                ("equip_Angle", models.FloatField()),
            ],
        ),
    ]
