# Generated by Django 4.0.5 on 2022-07-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradientSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgId', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('survey_Date', models.DateField()),
                ('survey_Type', models.CharField(choices=[('Flowing', 'Flowing'), ('Static', 'Static')], default='Static', max_length=20)),
                ('shutin_Period', models.FloatField()),
                ('tubinghead_Pressure', models.FloatField()),
                ('tubinghead_Temperature', models.FloatField()),
                ('liquid_Rate', models.FloatField()),
                ('water_Cut', models.FloatField()),
                ('gas_Oil_Ratio', models.FloatField()),
            ],
        ),
    ]
