# Generated by Django 4.1.4 on 2023-01-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opgradientsurveys", "0028_alter_gradientsurvey_survey_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradientsurvey",
            name="survey_Type",
            field=models.CharField(
                choices=[("Flowing", "Flowing"), ("Static", "Static")],
                default="Static",
                max_length=50,
            ),
        ),
    ]
