# Generated by Django 5.0.1 on 2024-02-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WIGradientSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifgId', models.PositiveIntegerField()),
                ('wiwellid', models.PositiveIntegerField()),
                ('wisurvey_Date', models.DateField()),
                ('wisurvey_Type', models.CharField(choices=[('Flowing', 'Flowing'), ('Static', 'Static')], default='Static', max_length=50)),
                ('wishutin_Period', models.FloatField()),
                ('witubinghead_Pressure', models.FloatField()),
                ('witubinghead_Temperature', models.FloatField()),
                ('wiliquid_Rate', models.FloatField()),
                ('wiwater_Cut', models.FloatField()),
                ('wigas_Oil_Ratio', models.FloatField()),
            ],
        ),
    ]
