# Generated by Django 4.1 on 2023-04-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_alter_asset_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
