# Generated by Django 5.0.1 on 2024-02-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='score',
            new_name='score_out_of_10',
        ),
    ]
