# Generated by Django 4.1.4 on 2023-02-14 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CementPlug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wellid", models.PositiveBigIntegerField()),
                ("fgid", models.PositiveBigIntegerField()),
                ("plug_Date", models.DateField()),
                ("plug_Top", models.FloatField()),
                ("plug_Bottom", models.FloatField()),
                ("cement_Density", models.FloatField()),
                ("cement_Volume", models.FloatField()),
                (
                    "plug_Description",
                    models.TextField(blank=True, max_length=2500, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PumpingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wellid", models.PositiveBigIntegerField()),
                ("fgid", models.PositiveBigIntegerField()),
                ("pump_Time", models.TimeField()),
                (
                    "pump_Fluid",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pre_Flush", "Pre_Flush"),
                            ("Slurry", "Slurry"),
                            ("Post_Flush", "Post_Flush"),
                            ("Water", "Water"),
                        ],
                        default="Pre_Flush",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("pump_Fluid_Density", models.FloatField()),
                ("pump_Pressure", models.FloatField()),
                ("pump_Rate", models.FloatField()),
                (
                    "cementplug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cementplugs.cementplug",
                    ),
                ),
            ],
        ),
    ]
