# Generated by Django 5.0.1 on 2024-03-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridgeplugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgeplug',
            name='plug_Make',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bridgeplug',
            name='plug_Model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bridgeplug',
            name='setting_range_ppf',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
