# Generated by Django 4.2.1 on 2023-06-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressureBuildupTestDesignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('design_Date', models.DateField()),
                ('design_Rate', models.FloatField()),
                ('layer_Thickness', models.FloatField()),
                ('layer_Permeability', models.FloatField()),
                ('mu_oil', models.FloatField()),
                ('total_Compressibility', models.FloatField()),
            ],
        ),
    ]
