# Generated by Django 4.1.4 on 2023-02-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coiltubingoperations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coiltubingoperation",
            name="totalhrs",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
