# Generated by Django 3.0.14 on 2022-05-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilproducers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilproducer',
            name='fgid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oilproducer',
            name='artificiallifttype',
            field=models.CharField(choices=[('Self', 'Self Flow'), ('GL', 'Gas Lift'), ('ESP', 'ESP'), ('SRP', 'SRP'), ('PCP', 'PCP'), ('Jetpump', 'Jet Pump')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='oilproducer',
            name='completiontype',
            field=models.CharField(choices=[('single', 'Single'), ('Dual', 'Dual'), ('Multilateral', 'Multilateral')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='oilproducer',
            name='connectedgatheringstation',
            field=models.CharField(choices=[('GS-1', 'GS-1'), ('GS-2', 'GS-2'), ('GS-3', 'GS-3'), ('GS-4', 'GS-4'), ('GS-5', 'GS-5'), ('GS-6', 'GS-6')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='oilproducer',
            name='connectedheader',
            field=models.CharField(choices=[('Header1', 'Header-1'), ('header2', 'Header-2'), ('header3', 'Header-3'), ('header4', 'Header-4'), ('header5', 'Header-5'), ('header6', 'Header-6')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='oilproducer',
            name='deviationtype',
            field=models.CharField(choices=[('Vertical', 'Vertical'), ('Deviated', 'Deviated'), ('Horizontal', 'Horizontal')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='oilproducer',
            name='inflowtype',
            field=models.CharField(choices=[('PI', 'Productivity Index'), ('Vogel', 'Vogel'), ('Standing', "Standing's"), ('Wiggins', 'Wiggins'), ('MultiRate', 'Multirate'), ('Darcy', 'Darcy')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='oilproducer',
            name='unitid',
            field=models.CharField(choices=[('Field', 'Field Units'), ('SI', 'SI Units'), ('MKS', 'MKS units'), ('User', 'User Selected')], default='1', max_length=20),
        ),
    ]
