# Generated by Django 4.1 on 2023-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oilproducers", "0004_alter_oilproducer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="oilproducer",
            name="category",
            field=models.CharField(
                choices=[
                    ("Exploratory", "Exploratory"),
                    ("Appraisal", "Appraisal"),
                    ("Development", "Development"),
                ],
                default="Development",
                max_length=50,
            ),
        ),
    ]
