# Generated by Django 5.0.1 on 2024-02-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WIOilShowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifgId', models.PositiveIntegerField()),
                ('wiwellid', models.PositiveIntegerField()),
                ('wiformation', models.CharField(max_length=100)),
                ('witop_MD', models.FloatField()),
                ('wibottom_MD', models.FloatField()),
                ('wisample_Type', models.CharField(max_length=100)),
                ('wisample_Description', models.CharField(max_length=500)),
                ('wiremarks', models.CharField(max_length=100)),
            ],
        ),
    ]
