# Generated by Django 4.2.1 on 2023-05-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constantpressuredrawdowntestanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constantpressuredrawdowntest',
            name='pwf',
            field=models.FloatField(default=1500),
            preserve_default=False,
        ),
    ]
