# Generated by Django 4.1.4 on 2023-01-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rigless", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rigless",
            name="unitname",
            field=models.CharField(max_length=50),
        ),
    ]
