# Generated by Django 5.0.1 on 2024-02-09 15:20

import django.db.models.deletion
import gicementbondlogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gicasings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GICementBondLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifgid', models.PositiveIntegerField()),
                ('giwellid', models.PositiveIntegerField()),
                ('gianalyst', models.CharField(max_length=30)),
                ('girecorded_date', models.DateField()),
                ('giinterpretation', models.TextField()),
                ('gicblImage', models.ImageField(blank=True, null=True, upload_to=gicementbondlogs.models.filepath)),
                ('gicasingSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gicasings.gicasingsizemodel')),
            ],
        ),
    ]
