# Generated by Django 4.1.4 on 2023-02-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fish", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishmodel",
            name="fish_Description",
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
    ]
