# Generated by Django 5.0.1 on 2024-02-16 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obgradientsurveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBGradientSurveyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obwellid', models.PositiveIntegerField()),
                ('obgauge_Depth', models.FloatField()),
                ('obgauge_Pressure', models.FloatField()),
                ('obgauge_Temperature', models.FloatField()),
                ('obgradientsurvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obgradientsurveys.obgradientsurvey')),
            ],
        ),
    ]
