# Generated by Django 5.0.1 on 2024-02-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPReservoirPressureEstimationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgid', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpanalysis_Date', models.DateField()),
                ('gplayer_Permeability', models.FloatField()),
                ('gplayer_Thickness', models.FloatField()),
                ('gplayer_Porosity', models.FloatField()),
                ('gptotal_Compressibility', models.FloatField()),
                ('gpmu_oil', models.FloatField()),
                ('gpoil_FVF', models.FloatField()),
                ('gpwellbore_Radius', models.FloatField()),
                ('gpoil_Prod_Rate', models.FloatField()),
                ('gpini_Res_Pres', models.FloatField()),
                ('gpdrainage_Radius', models.FloatField()),
            ],
        ),
    ]
