# Generated by Django 4.0.5 on 2022-07-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OPReservoirPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgId', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('survey_Date', models.DateField()),
                ('survey_Type', models.CharField(choices=[('NONE', 'None'), ('RFT', 'Rft'), ('DST', 'Dst'), ('PBU', 'Pbu'), ('SHUTIN', 'Shutin')], default='1', max_length=20)),
                ('gauge_Depth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gauge_Pressure', models.DecimalField(decimal_places=3, max_digits=10)),
                ('datum_Depth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('datum_Pressure', models.DecimalField(decimal_places=3, max_digits=10)),
                ('layer_permeability', models.DecimalField(decimal_places=3, max_digits=10)),
                ('layer_Thickness', models.DecimalField(decimal_places=3, max_digits=10)),
                ('layer_Skin', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
