# Generated by Django 5.0.1 on 2024-02-09 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wicasings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WILeakoffTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifgid', models.PositiveIntegerField()),
                ('wiwellid', models.PositiveIntegerField()),
                ('wianalyst', models.CharField(max_length=30)),
                ('wirecorded_Date', models.DateField()),
                ('wimudWeight', models.FloatField()),
                ('wiopenholeLength', models.FloatField()),
                ('wicasingSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wicasings.wicasingsizemodel')),
            ],
        ),
    ]
