# Generated by Django 5.0.1 on 2024-02-05 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('giwellobjectives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GIWellobjectivedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giwellid', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('gas_inj_rate_mmscfd', models.FloatField(blank=True, null=True)),
                ('gas_inj_pressure', models.FloatField(blank=True, null=True)),
                ('co2_percentage', models.FloatField(blank=True, null=True)),
                ('h2s_percentage', models.FloatField(blank=True, null=True)),
                ('giwellobjective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giwellobjectives.giwellobjective')),
            ],
        ),
    ]
