# Generated by Django 5.0.1 on 2024-02-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPWellcompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgid', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpequipment', models.CharField(choices=[('Tubing', 'Tubing'), ('PupJoint', 'PupJoint'), ('FlowCoupling', 'FlowCoupling'), ('SSD', 'SSD'), ('WEG', 'WEG'), ('SCSSSV', 'SCSSSV'), ('TCPGuns', 'TCPGuns'), ('Packer', 'Packer'), ('LandingNipple', 'LandingNipple'), ('BlastJoint', 'BlastJoint'), ('PerforatedPupJoint', 'PerforatedPupJoint'), ('Tubing_end', 'Tubing_end'), ('PlugbackDepth', 'PlugbackDepth'), ('Hold_up_Depth', 'Hold_up_Depth')], default='Single', max_length=50)),
                ('gpequip_Od', models.FloatField()),
                ('gpequip_Id', models.FloatField()),
                ('gpequip_Md', models.FloatField()),
                ('gpequip_Tvd', models.FloatField()),
                ('gpequip_Angle', models.FloatField()),
            ],
        ),
    ]
