# Generated by Django 5.0.1 on 2024-02-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPFormatioPressureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgId', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpstat_Group', models.CharField(max_length=100)),
                ('gpstat_Formation', models.CharField(max_length=100)),
                ('gpstat_Member', models.CharField(max_length=100)),
                ('gpmeasured_Depth', models.FloatField()),
                ('gppressure', models.FloatField()),
                ('gpporosity', models.FloatField()),
                ('gppermeability', models.FloatField()),
                ('gptemperature', models.FloatField()),
                ('gpremarks', models.CharField(max_length=100)),
            ],
        ),
    ]
