# Generated by Django 5.0.1 on 2024-02-09 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gidrillingsummary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GIDrillingProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifgId', models.PositiveIntegerField()),
                ('giwellid', models.PositiveIntegerField()),
                ('giops_Date', models.DateField()),
                ('gihole_Size', models.CharField(choices=[('26_inch', '26_inch'), ('20_inch', '20_inch'), ('16_inch', '16_inch'), ('12_1/4_inch', '12_1/4_inch'), ('8_1/2_inch', '8_1/2_inch'), ('6_1/8_inch', '6_1/8_inch'), ('4_1/2_inch', '4_1/2_inch')], default='12_1/4_inch', max_length=50)),
                ('gidepth_From', models.FloatField()),
                ('gidepth_To', models.FloatField()),
                ('gidescription', models.TextField(max_length=2500)),
                ('gipossible_reason', models.TextField(max_length=2500)),
                ('gidrillingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gidrillingsummary.gidrillingsummary')),
            ],
        ),
    ]
