# Generated by Django 4.1.4 on 2023-02-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drawdowntestanalysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawdowntest",
            name="file_Name",
            field=models.FileField(default=1, upload_to=""),
            preserve_default=False,
        ),
    ]
