# Generated by Django 4.1.4 on 2023-02-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drawdowntestanalysis", "0002_drawdowntest_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawdowntest",
            name="file_Name",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
