# Generated by Django 4.1.4 on 2023-02-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drawdowntestanalysis", "0005_drawdowntest_test_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawdowntest",
            name="guess_Value",
            field=models.PositiveBigIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="drawdowntest",
            name="liquid_Rate",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
