# Generated by Django 4.2.1 on 2023-05-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawdowntestanalysis', '0007_drawdowntest_fbhp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawdowntest',
            name='pvt_Well',
            field=models.CharField(max_length=50),
        ),
    ]
