# Generated by Django 4.2.1 on 2023-05-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawdowntestanalysis', '0008_alter_drawdowntest_pvt_well'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawdowntest',
            name='pvt_Well',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
