# Generated by Django 4.1.4 on 2023-03-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReservoirPressureEstimationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fgid", models.PositiveIntegerField()),
                ("wellid", models.PositiveIntegerField()),
                ("analysis_Date", models.DateField()),
                ("layer_Permeability", models.FloatField()),
                ("layer_Thickness", models.FloatField()),
                ("layer_Porosity", models.FloatField()),
                ("total_Compressibility", models.FloatField()),
                ("mu_oil", models.FloatField()),
                ("oil_FVF", models.FloatField()),
                ("wellbore_Radius", models.FloatField()),
                ("oil_Prod_Rate", models.FloatField()),
                ("ini_Res_Pres", models.FloatField()),
                ("drainage_Radius", models.FloatField()),
            ],
        ),
    ]
