# Generated by Django 5.0.1 on 2024-02-09 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WICementPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiwellid', models.PositiveBigIntegerField()),
                ('wifgid', models.PositiveBigIntegerField()),
                ('wiplug_Date', models.DateField()),
                ('wiplug_Top', models.FloatField()),
                ('wiplug_Bottom', models.FloatField()),
                ('wicement_Density', models.FloatField()),
                ('wicement_Volume', models.FloatField()),
                ('wiplug_Description', models.TextField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WIPumpingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiwellid', models.PositiveBigIntegerField()),
                ('wifgid', models.PositiveBigIntegerField()),
                ('wipump_Time', models.TimeField()),
                ('wipump_Fluid', models.CharField(blank=True, choices=[('Pre_Flush', 'Pre_Flush'), ('Slurry', 'Slurry'), ('Post_Flush', 'Post_Flush'), ('Water', 'Water')], default='Pre_Flush', max_length=20, null=True)),
                ('wipump_Fluid_Density', models.FloatField()),
                ('wipump_Pressure', models.FloatField()),
                ('wipump_Rate', models.FloatField()),
                ('wicementplug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wicementplugs.wicementplug')),
            ],
        ),
    ]
