# Generated by Django 5.0.1 on 2024-02-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WIRigworkover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifgid', models.IntegerField()),
                ('wiwellid', models.IntegerField()),
                ('wirigname', models.CharField(max_length=50)),
                ('wistart_Date', models.DateField()),
                ('wiend_Date', models.DateField()),
                ('wiexpected_liquid', models.FloatField()),
                ('wiexpected_WC', models.FloatField()),
                ('wiexpected_GOR', models.FloatField()),
                ('wipre_wor_liquid', models.FloatField()),
                ('wipre_wor_WC', models.FloatField()),
                ('wipre_wor_GOR', models.FloatField()),
                ('wipre_wor_Lift', models.CharField(choices=[('Self', 'Self Flow'), ('GL', 'Gas Lift'), ('ESP', 'ESP'), ('SRP', 'SRP'), ('PCP', 'PCP'), ('Jetpump', 'Jet Pump')], default='1', max_length=20)),
                ('wipost_wor_liquid', models.FloatField()),
                ('wipost_wor_WC', models.FloatField()),
                ('wipost_wor_GOR', models.FloatField()),
                ('wipost_wor_Lift', models.CharField(choices=[('Self', 'Self Flow'), ('GL', 'Gas Lift'), ('ESP', 'ESP'), ('SRP', 'SRP'), ('PCP', 'PCP'), ('Jetpump', 'Jet Pump')], default='1', max_length=20)),
                ('wijobsummary', models.TextField(max_length=1000)),
            ],
        ),
    ]
