# Generated by Django 4.2.1 on 2023-12-16 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_alter_asset_area'),
        ('blocks', '0003_alter_block_area'),
        ('oilfields', '0003_alter_oilfield_area_alter_oilfield_description_and_more'),
        ('sublayers', '0003_alter_sublayer_area_alter_sublayer_description_and_more'),
        ('layers', '0004_alter_layer_area_alter_layer_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellname', models.CharField(max_length=50)),
                ('fgid', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('Exploratory', 'Exploratory'), ('Appraisal', 'Appraisal'), ('Development', 'Development')], default='Development', max_length=50)),
                ('completiontype', models.CharField(choices=[('Single', 'Single'), ('Dual', 'Dual'), ('Multilateral', 'Multilateral')], default='1', max_length=20)),
                ('deviationtype', models.CharField(choices=[('Vertical', 'Vertical'), ('Deviated', 'Deviated'), ('Horizontal', 'Horizontal')], default='1', max_length=20)),
                ('inflowtype', models.CharField(choices=[('PI', 'Productivity Index'), ('Vogel', 'Vogel'), ('Standing', "Standing's"), ('Wiggins', 'Wiggins'), ('MultiRate', 'Multirate'), ('Darcy', 'Darcy')], default='1', max_length=20)),
                ('connectedgatheringstation', models.CharField(choices=[('GGS-1', 'GGS-1'), ('GGS-2', 'GGS-2'), ('GGS-3', 'GGS-3'), ('GGS-4', 'GGS-4'), ('GGS-5', 'GGS-5'), ('GGS-6', 'GGS-6')], default='1', max_length=20)),
                ('connectedheader', models.CharField(choices=[('Header1', 'Header-1'), ('header2', 'Header-2'), ('header3', 'Header-3'), ('header4', 'Header-4'), ('header5', 'Header-5'), ('header6', 'Header-6')], default='1', max_length=20)),
                ('unitid', models.CharField(choices=[('Field', 'Field Units'), ('SI', 'SI Units'), ('MKS', 'MKS units'), ('User', 'User Selected')], default='1', max_length=20)),
                ('is_selected', models.BooleanField()),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.block')),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.layer')),
                ('oilfield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oilfields.oilfield')),
                ('sublayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sublayers.sublayer')),
            ],
        ),
    ]
