# Generated by Django 5.0.1 on 2024-02-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBTestResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obfgId', models.PositiveIntegerField()),
                ('obwellid', models.PositiveIntegerField()),
                ('obformation', models.CharField(max_length=100)),
                ('obtop_MD', models.FloatField()),
                ('obbottom_MD', models.FloatField()),
                ('obtest_Duration', models.FloatField()),
                ('obchoke_Size', models.CharField(max_length=100)),
                ('obthp', models.FloatField()),
                ('obbhp', models.FloatField()),
                ('obliquid_Rate', models.FloatField()),
                ('oboil_Rate', models.FloatField()),
                ('obgas_Rate', models.FloatField()),
                ('obwater_Cut', models.FloatField()),
                ('obremarks', models.CharField(max_length=100)),
            ],
        ),
    ]
