# Generated by Django 4.0.5 on 2022-07-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casings', '0007_alter_casingmodel_casinggrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CementBondLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('analyst', models.CharField(max_length=30)),
                ('recorded_date', models.DateField()),
                ('interpretation', models.TextField()),
                ('cblImage', models.ImageField(upload_to='home/static/home/images/cementbondlogs')),
                ('casingSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casings.casingsizemodel')),
            ],
        ),
    ]
