# Generated by Django 4.0.5 on 2022-07-10 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casings', '0007_alter_casingmodel_casinggrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakoffTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('analyst', models.CharField(max_length=30)),
                ('recorded_Date', models.DateField()),
                ('mudWeight', models.FloatField()),
                ('openholeLength', models.FloatField()),
                ('casingSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casings.casingsizemodel')),
            ],
        ),
        migrations.CreateModel(
            name='LeakoffTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('volume', models.FloatField()),
                ('pressure', models.FloatField()),
                ('casingSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casings.casingsizemodel')),
                ('leakoffTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leakoffTests.leakofftest')),
            ],
        ),
    ]
