# Generated by Django 5.0.1 on 2024-03-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leakoffTests', '0002_delete_leakofftestdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='leakofftest',
            name='casingModelid',
            field=models.PositiveBigIntegerField(default=34),
            preserve_default=False,
        ),
    ]
