# Generated by Django 5.0.1 on 2024-02-16 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wigradientsurveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WIGradientSurveyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiwellid', models.PositiveIntegerField()),
                ('wigauge_Depth', models.FloatField()),
                ('wigauge_Pressure', models.FloatField()),
                ('wigauge_Temperature', models.FloatField()),
                ('wigradientsurvey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wigradientsurveys.wigradientsurvey')),
            ],
        ),
    ]
