# Generated by Django 5.0.1 on 2024-02-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPDrillingWellData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgId', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpsurvey_Date', models.DateField()),
                ('gprkb_to_WH', models.FloatField()),
                ('gprkb_to_GL', models.FloatField()),
                ('gpgl_to_MSL', models.FloatField()),
                ('gprkb_to_MSL', models.FloatField()),
                ('gpwh_to_MSL', models.FloatField()),
                ('gplattitude', models.CharField(max_length=20)),
                ('gplongitude', models.CharField(max_length=20)),
                ('gptotal_Measured_Depth', models.FloatField()),
                ('gptotal_True_Vertical_Depth', models.FloatField()),
                ('gpafe_No', models.CharField(max_length=40)),
            ],
        ),
    ]
