# Generated by Django 5.0.1 on 2024-02-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GIGradientSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifgId', models.PositiveIntegerField()),
                ('giwellid', models.PositiveIntegerField()),
                ('gisurvey_Date', models.DateField()),
                ('gisurvey_Type', models.CharField(choices=[('Floging', 'Floging'), ('Static', 'Static')], default='Static', max_length=50)),
                ('gishutin_Period', models.FloatField()),
                ('gitubinghead_Pressure', models.FloatField()),
                ('gitubinghead_Temperature', models.FloatField()),
                ('giliquid_Rate', models.FloatField()),
                ('giwater_Cut', models.FloatField()),
                ('gigas_Oil_Ratio', models.FloatField()),
            ],
        ),
    ]
