# Generated by Django 5.0.1 on 2024-02-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WIReservoirPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifgId', models.PositiveIntegerField()),
                ('wiwellid', models.PositiveIntegerField()),
                ('wisurvey_Date', models.DateField()),
                ('wisurvey_Type', models.CharField(choices=[('NONE', 'None'), ('RFT', 'Rft'), ('DST', 'Dst'), ('PBU', 'Pbu'), ('SHUTIN', 'Shutin')], default='1', max_length=20)),
                ('wigauge_Depth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('wigauge_Pressure', models.DecimalField(decimal_places=3, max_digits=10)),
                ('widatum_Depth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('widatum_Pressure', models.DecimalField(decimal_places=3, max_digits=10)),
                ('wilayer_permeability', models.DecimalField(decimal_places=3, max_digits=10)),
                ('wilayer_Thickness', models.DecimalField(decimal_places=3, max_digits=10)),
                ('wilayer_Skin', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
