# Generated by Django 5.0.1 on 2024-02-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPRigworkover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgid', models.IntegerField()),
                ('gpwellid', models.IntegerField()),
                ('gprigname', models.CharField(max_length=50)),
                ('gpstart_Date', models.DateField()),
                ('gpend_Date', models.DateField()),
                ('gpexpected_liquid', models.FloatField()),
                ('gpexpected_WC', models.FloatField()),
                ('gpexpected_GOR', models.FloatField()),
                ('gppre_wor_liquid', models.FloatField()),
                ('gppre_wor_WC', models.FloatField()),
                ('gppre_wor_GOR', models.FloatField()),
                ('gppre_wor_Lift', models.CharField(choices=[('Self', 'Self Flow'), ('GL', 'Gas Lift'), ('ESP', 'ESP'), ('SRP', 'SRP'), ('PCP', 'PCP'), ('Jetpump', 'Jet Pump')], default='1', max_length=20)),
                ('gppost_wor_liquid', models.FloatField()),
                ('gppost_wor_WC', models.FloatField()),
                ('gppost_wor_GOR', models.FloatField()),
                ('gppost_wor_Lift', models.CharField(choices=[('Self', 'Self Flow'), ('GL', 'Gas Lift'), ('ESP', 'ESP'), ('SRP', 'SRP'), ('PCP', 'PCP'), ('Jetpump', 'Jet Pump')], default='1', max_length=20)),
                ('gpjobsummary', models.TextField(max_length=1000)),
            ],
        ),
    ]
