# Generated by Django 5.0.1 on 2024-02-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBRigworkover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obfgid', models.IntegerField()),
                ('obwellid', models.IntegerField()),
                ('obrigname', models.CharField(max_length=50)),
                ('obstart_Date', models.DateField()),
                ('obend_Date', models.DateField()),
                ('obexpected_liquid', models.FloatField()),
                ('obexpected_WC', models.FloatField()),
                ('obexpected_GOR', models.FloatField()),
                ('obpre_wor_liquid', models.FloatField()),
                ('obpre_wor_WC', models.FloatField()),
                ('obpre_wor_GOR', models.FloatField()),
                ('obpre_wor_Lift', models.CharField(choices=[('Self', 'Self Flow'), ('GL', 'Gas Lift'), ('ESP', 'ESP'), ('SRP', 'SRP'), ('PCP', 'PCP'), ('Jetpump', 'Jet Pump')], default='1', max_length=20)),
                ('obpost_wor_liquid', models.FloatField()),
                ('obpost_wor_WC', models.FloatField()),
                ('obpost_wor_GOR', models.FloatField()),
                ('obpost_wor_Lift', models.CharField(choices=[('Self', 'Self Flow'), ('GL', 'Gas Lift'), ('ESP', 'ESP'), ('SRP', 'SRP'), ('PCP', 'PCP'), ('Jetpump', 'Jet Pump')], default='1', max_length=20)),
                ('objobsummary', models.TextField(max_length=1000)),
            ],
        ),
    ]
