# Generated by Django 4.2.1 on 2023-05-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deviationsurveydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgId', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('measuredDepth', models.FloatField()),
                ('angle', models.FloatField()),
                ('azimuth', models.FloatField()),
                ('tvd', models.FloatField()),
                ('northSouth', models.FloatField()),
                ('eastWest', models.FloatField()),
                ('netDrift', models.FloatField()),
                ('netDirection', models.FloatField()),
                ('verticalSection', models.FloatField()),
                ('dogLeg', models.FloatField()),
            ],
        ),
    ]
