# Generated by Django 4.2.1 on 2023-05-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviationsurveydata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviationsurveydata',
            name='dogLeg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviationsurveydata',
            name='eastWest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviationsurveydata',
            name='netDirection',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviationsurveydata',
            name='netDrift',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviationsurveydata',
            name='northSouth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviationsurveydata',
            name='tvd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviationsurveydata',
            name='verticalSection',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
