# Generated by Django 5.0.1 on 2024-02-09 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('widrillingsummary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WIDrillingOps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifgId', models.PositiveIntegerField()),
                ('wiwellid', models.PositiveIntegerField()),
                ('wiops_Date', models.DateField()),
                ('witime_From', models.TimeField()),
                ('witime_To', models.TimeField()),
                ('witotalhrs', models.FloatField()),
                ('wiops_Code', models.CharField(choices=[('BOPTest', 'BOPTest'), ('CasingRun', 'CasingRun'), ('Cementing', 'Cementing'), ('CementSqueeze', 'CementSqueeze'), ('Circulation', 'Circulation'), ('CoilTubing', 'CoilTubing'), ('Conditioning', 'Conditioning'), ('Coring', 'Coring'), ('DeviationSurvey', 'DeviationSurvey'), ('Drilling', 'Drilling'), ('DrillStemTest', 'DrillStemTest'), ('Fishing', 'Fishing'), ('NonProductive', 'NonProductive'), ('OperatingStatus', 'OperatingStatus'), ('Others', 'Others'), ('Perforating', 'Perforating'), ('PlugBack', 'PlugBack'), ('Reaming', 'Reaming'), ('RigDownBOP', 'RigDownBOP'), ('RigMove', 'RigMove'), ('Rigup', 'Rigup'), ('RigMaintenance', 'RigMaintenance'), ('RigRepair', 'RigRepair'), ('RigUpBOP', 'RigUpBOP'), ('ReplaceDrillingLine', 'ReplaceDrillingLine'), ('TearDown', 'TearDown'), ('TripIn', 'TripIn'), ('TripOut', 'TripOut'), ('WaitOnCement', 'WaitOnCement'), ('WaitOnWeather', 'WaitOnWeather'), ('WirelineLogs', 'WirelineLogs'), ('RunRiserEquipment', 'RunRiserEquipment'), ('RetrieveRiserEquipment', 'RetrieveRiserEquipment'), ('Safety', 'Safety'), ('SubSeaInstallation', 'SubSeaInstallation'), ('SurfaceTesting', 'SurfaceTesting'), ('Swabbing', 'Swabbing'), ('Testing', 'Testing'), ('Treating', 'Treating'), ('TubingTrip', 'TubingTrip'), ('WellCompletion', 'WellCompletion'), ('WellControl', 'WellControl')], default='Drilling', max_length=50)),
                ('wiops_Summary', models.TextField(max_length=2000)),
                ('widrillingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widrillingsummary.widrillingsummary')),
            ],
        ),
    ]
