# Generated by Django 4.1 on 2023-04-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oilfields", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oilfield",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
