# Generated by Django 5.0.1 on 2024-02-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilfields', '0003_alter_oilfield_area_alter_oilfield_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilfield',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
