# Generated by Django 4.2.1 on 2023-06-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgId', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('formation', models.CharField(max_length=100)),
                ('test_Date', models.DateField()),
                ('test_Duration', models.FloatField()),
                ('choke_Size', models.CharField(max_length=100)),
                ('th_Pres', models.FloatField()),
                ('th_Temp', models.FloatField()),
                ('liquid_Rate', models.FloatField()),
                ('oil_Rate', models.FloatField()),
                ('gas_Rate', models.FloatField()),
                ('fl_Pres', models.FloatField()),
                ('fl_Temp', models.FloatField()),
                ('sep_Pres', models.FloatField()),
                ('sep_Temp', models.FloatField()),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
