# Generated by Django 5.0.1 on 2024-02-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBCasingGradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obcasingGrade', models.CharField(max_length=20)),
                ('obcollapsePressure', models.DecimalField(decimal_places=3, max_digits=10)),
                ('obburstPressure', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OBCasingSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obcasingSize', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OBCasingWeightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obcasingWeight', models.CharField(max_length=20)),
                ('obcasingID', models.DecimalField(decimal_places=3, max_digits=10)),
                ('obcasingSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obcasings.obcasingsizemodel')),
            ],
        ),
        migrations.CreateModel(
            name='OBCasingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obfgid', models.PositiveIntegerField()),
                ('obwellid', models.PositiveIntegerField()),
                ('obcasingType', models.CharField(blank=True, choices=[('Surface', 'Surface'), ('Conductor', 'Conductor'), ('Internediate_1', 'Internediate1'), ('Intermediate_2', 'Intermediate2'), ('Intermediate_3', 'Intermediate2'), ('Liner_casing', 'Linercasing'), ('Production_Casing', 'ProductionCasing'), ('Production_Liner', 'ProductionLiner')], default='Surface', max_length=20, null=True)),
                ('obcasingID', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('obcollapsePressure', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('obburstPressure', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('obthreadType', models.CharField(blank=True, choices=[('1', 'STC'), ('2', 'LTC'), ('3', 'BTC'), ('4', 'LP'), ('5', 'EUE'), ('6', 'NUE'), ('7', 'IJ'), ('8', 'VAM'), ('9', 'NEWVAM')], default='1', max_length=20, null=True)),
                ('obmaterial', models.CharField(blank=True, choices=[('1', 'Carbon_Steel'), ('2', 'CRA_9Cr'), ('3', 'CRA_13Cr'), ('4', 'Inconel')], default='1', max_length=20, null=True)),
                ('obshoedepth', models.FloatField()),
                ('obfloatCollar', models.FloatField()),
                ('obhangerDepth', models.FloatField()),
                ('obcementTop', models.FloatField()),
                ('obcasingGrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casingGrades', to='obcasings.obcasinggrademodel')),
                ('obcasingSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casingSizes', to='obcasings.obcasingsizemodel')),
                ('obcasingWeight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casingWeights', to='obcasings.obcasingweightmodel')),
            ],
        ),
        migrations.AddField(
            model_name='obcasinggrademodel',
            name='obcasingWeight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obcasings.obcasingweightmodel'),
        ),
    ]
