# Generated by Django 4.2.1 on 2023-05-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormatioPressureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgId', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('stat_Group', models.CharField(max_length=100)),
                ('stat_Formation', models.CharField(max_length=100)),
                ('stat_Member', models.CharField(max_length=100)),
                ('measured_Depth', models.FloatField()),
                ('pressure', models.FloatField()),
                ('porosity', models.FloatField()),
                ('permeability', models.FloatField()),
                ('temperature', models.FloatField()),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
