# Generated by Django 5.0.1 on 2024-03-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tubings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tubingmodel',
            name='angle',
        ),
        migrations.RemoveField(
            model_name='tubingmodel',
            name='tvd_From',
        ),
        migrations.RemoveField(
            model_name='tubingmodel',
            name='tvd_To',
        ),
    ]
