# Generated by Django 5.0.1 on 2024-03-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubings', '0002_remove_tubingmodel_angle_remove_tubingmodel_tvd_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubingmodel',
            name='angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tubingmodel',
            name='tvd_From',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tubingmodel',
            name='tvd_To',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
