# Generated by Django 5.0.1 on 2024-03-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tubings', '0003_tubingmodel_angle_tubingmodel_tvd_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tubingmodel',
            old_name='tvd_From',
            new_name='tvd_from',
        ),
    ]
