# Generated by Django 5.0.1 on 2024-03-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tubings', '0004_rename_tvd_from_tubingmodel_tvd_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tubingmodel',
            name='angle',
        ),
        migrations.RemoveField(
            model_name='tubingmodel',
            name='tvd_To',
        ),
        migrations.RemoveField(
            model_name='tubingmodel',
            name='tvd_from',
        ),
    ]
