# Generated by Django 5.0.1 on 2024-03-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tubings', '0005_remove_tubingmodel_angle_remove_tubingmodel_tvd_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubingmodel',
            name='angle_To',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tubingmodel',
            name='tvd_To',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
