# Generated by Django 5.0.1 on 2024-03-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiRatePBUdesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('survey_Date', models.DateField()),
                ('layer_Porosity_fraction', models.FloatField()),
                ('layer_Thickness_ft', models.FloatField()),
                ('wellbore_Radius_ft', models.FloatField()),
                ('total_Compressibility', models.FloatField()),
                ('initial_Res_Pres_psi', models.FloatField()),
                ('oil_Viscosity_cP', models.FloatField()),
                ('oil_FVF_Bo', models.FloatField()),
                ('time1', models.FloatField(blank=True, null=True)),
                ('rate1', models.FloatField(blank=True, null=True)),
                ('time2', models.FloatField(blank=True, null=True)),
                ('rate2', models.FloatField(blank=True, null=True)),
                ('time3', models.FloatField(blank=True, null=True)),
                ('rate3', models.FloatField(blank=True, null=True)),
                ('time4', models.FloatField(blank=True, null=True)),
                ('rate4', models.FloatField(blank=True, null=True)),
                ('time5', models.FloatField(blank=True, null=True)),
                ('rate5', models.FloatField(blank=True, null=True)),
                ('time6', models.FloatField(blank=True, null=True)),
                ('rate6', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
