# Generated by Django 5.0.1 on 2024-03-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiratepbudesign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiratepbudesign',
            name='drainage_radius_ft',
            field=models.FloatField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiratepbudesign',
            name='layer_Permeability_md',
            field=models.FloatField(default=600),
            preserve_default=False,
        ),
    ]
