# Generated by Django 4.0.5 on 2022-07-19 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('layers', '0001_initial'),
        ('blackoilpvt', '0015_alter_blackoilpvt_pbcorrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WigginsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('analysis_Date', models.DateField()),
                ('wiggins_Test_Rate', models.FloatField()),
                ('wiggins_Test_Pressure', models.FloatField()),
                ('current_Reservoir_Pressure', models.FloatField()),
                ('future_Reservoir_Pressure', models.FloatField()),
                ('water_Cut', models.FloatField()),
                ('layer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.layer')),
            ],
        ),
        migrations.CreateModel(
            name='VogelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('analysis_Date', models.DateField()),
                ('vogel_Test_Rate', models.FloatField()),
                ('vogel_Test_Pressure', models.FloatField()),
                ('reservoir_Pressure', models.FloatField()),
                ('layer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.layer')),
            ],
        ),
        migrations.CreateModel(
            name='StandingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('analysis_Date', models.DateField()),
                ('standings_Test_Rate', models.FloatField()),
                ('standings_Test_Pressure', models.FloatField()),
                ('reservoir_Pressure', models.FloatField()),
                ('relative_Permeability', models.FloatField()),
                ('layer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.layer')),
                ('pvt_Well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blackoilpvt.blackoilpvt')),
            ],
        ),
        migrations.CreateModel(
            name='ProductivityIndexModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('analysis_Date', models.DateField()),
                ('productivity_index', models.FloatField()),
                ('reservoir_Pressure', models.FloatField()),
                ('layer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.layer')),
            ],
        ),
        migrations.CreateModel(
            name='MultirateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('analysis_Date', models.DateField()),
                ('test_Rate1', models.FloatField()),
                ('test_Pressure1', models.FloatField()),
                ('test_Rate2', models.FloatField()),
                ('test_Pressure2', models.FloatField()),
                ('test_Rate3', models.FloatField()),
                ('test_Pressure3', models.FloatField()),
                ('current_Reservoir_Pressure', models.FloatField()),
                ('layer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.layer')),
            ],
        ),
        migrations.CreateModel(
            name='DarcyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('analysis_Date', models.DateField()),
                ('layer_Permeability', models.FloatField()),
                ('layer_Thickness', models.FloatField()),
                ('drainage_Radius', models.FloatField()),
                ('wellbore_Radius', models.FloatField()),
                ('layer_Skin', models.FloatField()),
                ('current_Reservoir_Pressure', models.FloatField()),
                ('layer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.layer')),
                ('pvt_Well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blackoilpvt.blackoilpvt')),
            ],
        ),
    ]
