# Generated by Django 4.0.5 on 2022-07-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sublayers', '0001_initial'),
        ('opinflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darcymodel',
            name='layer_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sublayers.sublayer'),
        ),
        migrations.AlterField(
            model_name='multiratemodel',
            name='layer_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sublayers.sublayer'),
        ),
        migrations.AlterField(
            model_name='productivityindexmodel',
            name='layer_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sublayers.sublayer'),
        ),
        migrations.AlterField(
            model_name='standingsmodel',
            name='layer_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sublayers.sublayer'),
        ),
        migrations.AlterField(
            model_name='vogelmodel',
            name='layer_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sublayers.sublayer'),
        ),
        migrations.AlterField(
            model_name='wigginsmodel',
            name='layer_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sublayers.sublayer'),
        ),
    ]
