# Generated by Django 4.0.5 on 2022-07-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackoilpvt', '0015_alter_blackoilpvt_pbcorrelation'),
        ('opinflow', '0002_alter_darcymodel_layer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiratemodel',
            name='pvt_Well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blackoilpvt.blackoilpvt'),
        ),
        migrations.AddField(
            model_name='productivityindexmodel',
            name='pvt_Well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blackoilpvt.blackoilpvt'),
        ),
        migrations.AddField(
            model_name='vogelmodel',
            name='pvt_Well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blackoilpvt.blackoilpvt'),
        ),
        migrations.AddField(
            model_name='wigginsmodel',
            name='pvt_Well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blackoilpvt.blackoilpvt'),
        ),
    ]
