# Generated by Django 4.0.5 on 2022-07-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinflow', '0003_multiratemodel_pvt_well_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standingsmodel',
            old_name='relative_Permeability',
            new_name='current_Relative_Permeability',
        ),
        migrations.RenameField(
            model_name='standingsmodel',
            old_name='reservoir_Pressure',
            new_name='current_Reservoir_Pressure',
        ),
        migrations.RenameField(
            model_name='standingsmodel',
            old_name='standings_Test_Pressure',
            new_name='current_Test_Pressure',
        ),
        migrations.RenameField(
            model_name='standingsmodel',
            old_name='standings_Test_Rate',
            new_name='current_Test_Rate',
        ),
        migrations.AddField(
            model_name='standingsmodel',
            name='future_Relative_Permeability',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standingsmodel',
            name='future_Reservoir_Pressure',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
