# Generated by Django 5.0.1 on 2024-02-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPPressuredropCalculationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgid', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpmodel_Date', models.DateField()),
                ('gpsource_Pressure', models.FloatField()),
                ('gpsource_Flowrate', models.FloatField()),
                ('gpsource_Temp', models.FloatField()),
                ('gppipe_Angle', models.FloatField()),
                ('gppipe_Length', models.FloatField()),
                ('gppipe_Diam', models.FloatField()),
                ('gpfluid_API', models.FloatField()),
                ('gpfluid_WaterCut', models.FloatField()),
                ('gpfluid_GOR', models.FloatField()),
                ('gpfluid_gas_spgr', models.FloatField()),
            ],
        ),
    ]
