# Generated by Django 5.0.1 on 2024-02-05 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obwellobjectives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBWellobjectivedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obwellid', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('perf_Depth', models.FloatField(blank=True, null=True)),
                ('res_pressure', models.FloatField(blank=True, null=True)),
                ('well_type', models.CharField(choices=[('Oilproducer', 'Oilproducer'), ('Gasproducer', 'Gasproducer'), ('Waterinjector', 'Waterinjector'), ('Gasinjector', 'Gasinjector'), ('Observer', 'Observer')], default='1', max_length=20)),
                ('obwellobjective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obwellobjectives.obwellobjective')),
            ],
        ),
    ]
