# Generated by Django 3.0.14 on 2022-06-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opwellobjectives', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OPWellobjectivedata',
        ),
    ]
