# Generated by Django 4.0.5 on 2022-06-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opwellobjectives', '0002_delete_opwellobjectivedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='opwellobjective',
            name='wellid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
