# Generated by Django 4.0.5 on 2022-06-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opwellobjectives', '0003_opwellobjective_wellid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opwellobjective',
            name='opfgid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='opwellobjective',
            name='wellid',
            field=models.PositiveIntegerField(),
        ),
    ]
