# Generated by Django 4.1 on 2023-04-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opwellobjectives", "0004_alter_opwellobjective_opfgid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opwellobjective",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
