# Generated by Django 5.0.1 on 2024-02-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBDrillingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obfgId', models.PositiveIntegerField()),
                ('obwellid', models.PositiveIntegerField()),
                ('obstart_Date', models.DateField()),
                ('obend_Date', models.DateField()),
                ('obliquid_Rate', models.FloatField()),
                ('obwater_Cut', models.FloatField()),
                ('obgas_Rate', models.FloatField()),
                ('oboil_Rate', models.FloatField()),
                ('obgas_Oil_Ratio', models.FloatField()),
                ('obdrilling_Summary', models.TextField(max_length=2000)),
            ],
        ),
    ]
