# Generated by Django 4.0.5 on 2022-06-15 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackoilPVT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgId', models.CharField(max_length=200)),
                ('wellName', models.TextField(max_length=1000)),
                ('sampleId', models.PositiveIntegerField(blank=True, null=True)),
                ('sampleDate', models.PositiveIntegerField(blank=True, null=True)),
                ('reservoirTemperature', models.CharField(max_length=200)),
                ('oilAPIgravity', models.TextField(max_length=1000)),
                ('gasGravity', models.TextField(max_length=1000)),
                ('solutionGOR', models.PositiveIntegerField(blank=True, null=True)),
                ('pbCorrelation', models.CharField(choices=[('Standing', 'Standing'), ('Glasso', 'Glasso'), ('Marhoun', 'Marhoun'), {'VasquezBeggs', 'Vasquez_Beggs'}, ('Petrosky_Farshad', 'PetroskyFarshad')], default='1', max_length=20)),
                ('viscosityCorrelation', models.CharField(choices=[('Beal', 'Beal'), ('Beggs_Robinson', 'Beggs_Robinson'), ('Glasso', 'Glasso')], default='1', max_length=20)),
                ('reservoirPressure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
    ]
