# Generated by Django 4.0.5 on 2022-06-15 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackoilpvt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackoilpvt',
            name='fgId',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='blackoilpvt',
            name='gasGravity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='blackoilpvt',
            name='oilAPIgravity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='blackoilpvt',
            name='reservoirPressure',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blackoilpvt',
            name='reservoirTemperature',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='blackoilpvt',
            name='sampleDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='blackoilpvt',
            name='sampleId',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blackoilpvt',
            name='solutionGOR',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blackoilpvt',
            name='wellName',
            field=models.CharField(max_length=1000),
        ),
    ]
