# Generated by Django 4.0.5 on 2022-06-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackoilpvt', '0002_alter_blackoilpvt_fgid_alter_blackoilpvt_gasgravity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackoilpvt',
            name='sampleDate',
            field=models.DateField(),
        ),
    ]
