# Generated by Django 4.0.5 on 2022-06-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackoilpvt', '0005_alter_blackoilpvt_pbcorrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackoilpvt',
            name='pbCorrelation',
            field=models.CharField(choices=[('Standing', 'Standing'), ('Glasso', 'Glasso'), ('Marhoun', 'Marhoun'), {'Vasquez_Beggs', 'VasquezBeggs'}, ('Petrosky_Farshad', 'PetroskyFarshad')], default='1', max_length=20),
        ),
    ]
