# Generated by Django 4.0.5 on 2022-06-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackoilpvt', '0006_alter_blackoilpvt_pbcorrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackoilpvt',
            name='viscosityCorrelation',
            field=models.CharField(choices=[('Beal', 'Beal'), ('Beggs_Robinson', 'BeggsRobinson'), ('Glasso', 'Glasso')], default='1', max_length=20),
        ),
    ]
