# Generated by Django 4.0.5 on 2022-06-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackoilpvt', '0007_alter_blackoilpvt_viscositycorrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackoilpvt',
            name='pbCorrelation',
            field=models.CharField(choices=[('Standing', 'Standing'), ('Glaso', 'Glaso'), ('Marhoun', 'Marhoun'), {'Vasquez_Beggs', 'VasquezBeggs'}, ('Petrosky_Farshad', 'PetroskyFarshad')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='blackoilpvt',
            name='viscosityCorrelation',
            field=models.CharField(choices=[('Beal', 'Beal'), ('Beggs_Robinson', 'BeggsRobinson'), ('Glaso', 'Glaso')], default='1', max_length=20),
        ),
    ]
