# Generated by Django 4.0.5 on 2022-06-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackoilpvt', '0010_alter_blackoilpvt_viscositycorrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackoilpvt',
            name='pbCorrelation',
            field=models.CharField(choices=[('_Standing', 'Standing'), ('_Glaso', 'Glaso'), ('_Marhoun', 'Marhoun'), {'VasquezBeggs', '_VasquezBeggs'}, ('_PetroskyFarshad', 'PetroskyFarshad')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='blackoilpvt',
            name='viscosityCorrelation',
            field=models.CharField(choices=[('_Beal', 'Beal'), ('_BeggsRobinson', 'BeggsRobinson'), ('_Glaso', 'Glaso')], default='1', max_length=20),
        ),
    ]
