# Generated by Django 4.0.5 on 2022-06-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackoilpvt', '0013_alter_blackoilpvt_viscositycorrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackoilpvt',
            name='pbCorrelation',
            field=models.CharField(choices=[('_Standing', 'Standing'), ('_Glaso', 'Glaso'), ('_Marhoun', 'Marhoun'), {'_VasquezBeggs', 'VasquezBeggs'}, ('_PetroskyFarshad', 'PetroskyFarshad')], default='_VasquezBeggs', max_length=20),
        ),
    ]
