# Generated by Django 4.0.5 on 2022-06-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackoilpvt', '0014_alter_blackoilpvt_pbcorrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackoilpvt',
            name='pbCorrelation',
            field=models.CharField(choices=[('_Standing', 'Standing'), ('_Glaso', 'Glaso'), ('_Marhoun', 'Marhoun'), ('_PetroskyFarshad', 'PetroskyFarshad'), {'VasquezBeggs', '_VasquezBeggs'}], default='_VasquezBeggs', max_length=20),
        ),
    ]
