# Generated by Django 4.0.5 on 2022-07-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackoilpvt', '0016_blackoilpvt_sublayer_alter_blackoilpvt_wellname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blackoilpvt',
            name='pbCorrelation',
            field=models.CharField(choices=[('_Standing', 'Standing'), {'_VasquezBeggs', 'VasquezBeggs'}, ('_Glaso', 'Glaso'), ('_Marhoun', 'Marhoun'), ('_PetroskyFarshad', 'PetroskyFarshad')], default='_VasquezBeggs', max_length=20),
        ),
    ]
