# Generated by Django 4.1 on 2023-05-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blackoilpvt", "0018_alter_blackoilpvt_pbcorrelation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blackoilpvt",
            name="gasGravity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="blackoilpvt",
            name="oilAPIgravity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="blackoilpvt",
            name="reservoirPressure",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="blackoilpvt",
            name="reservoirTemperature",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="blackoilpvt",
            name="solutionGOR",
            field=models.FloatField(),
        ),
    ]
