# Generated by Django 4.1.4 on 2023-01-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rigworkover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fgid", models.PositiveIntegerField()),
                ("wellid", models.PositiveIntegerField()),
                ("rigname", models.TextField(max_length=50)),
                ("start_Date", models.DateField()),
                ("end_Date", models.DateField()),
                ("expected_liquid", models.FloatField()),
                ("expected_WC", models.FloatField()),
                ("expected_GOR", models.FloatField()),
                ("pre_wor_liquid", models.FloatField()),
                ("pre_wor_WC", models.FloatField()),
                ("pre_wor_GOR", models.FloatField()),
                (
                    "pre_wor_Lift",
                    models.CharField(
                        choices=[
                            ("Self", "Self Flow"),
                            ("GL", "Gas Lift"),
                            ("ESP", "ESP"),
                            ("SRP", "SRP"),
                            ("PCP", "PCP"),
                            ("Jetpump", "Jet Pump"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                ("post_wor_liquid", models.FloatField()),
                ("post_wor_WC", models.FloatField()),
                ("post_wor_GOR", models.FloatField()),
                (
                    "post_wor_Lift",
                    models.CharField(
                        choices=[
                            ("Self", "Self Flow"),
                            ("GL", "Gas Lift"),
                            ("ESP", "ESP"),
                            ("SRP", "SRP"),
                            ("PCP", "PCP"),
                            ("Jetpump", "Jet Pump"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                ("jobsummary", models.TextField(max_length=1000)),
            ],
        ),
    ]
