# Generated by Django 4.1.4 on 2023-01-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rigworkover", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rigworkover",
            name="fgid",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="rigworkover",
            name="rigname",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="rigworkover",
            name="wellid",
            field=models.IntegerField(),
        ),
    ]
