# Generated by Django 4.1.4 on 2023-01-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fgid", models.PositiveIntegerField()),
                ("wellid", models.PositiveIntegerField()),
                ("unitname", models.TextField(max_length=50)),
                ("start_Date", models.DateField()),
                ("end_Date", models.DateField()),
                ("expected_liquid", models.FloatField()),
                ("expected_WC", models.FloatField()),
                ("expected_GOR", models.FloatField()),
                ("pre_stim_liquid", models.FloatField()),
                ("pre_stim_WC", models.FloatField()),
                ("pre_stim_GOR", models.FloatField()),
                ("post_stim_liquid", models.FloatField()),
                ("post_stim_WC", models.FloatField()),
                ("post_stim_GOR", models.FloatField()),
                ("jobsummary", models.TextField(max_length=1000)),
            ],
        ),
    ]
