# Generated by Django 5.0.1 on 2024-02-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPReservoirPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgId', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpsurvey_Date', models.DateField()),
                ('gpsurvey_Type', models.CharField(choices=[('NONE', 'None'), ('RFT', 'Rft'), ('DST', 'Dst'), ('PBU', 'Pbu'), ('SHUTIN', 'Shutin')], default='1', max_length=20)),
                ('gpgauge_Depth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gpgauge_Pressure', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gpdatum_Depth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gpdatum_Pressure', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gplayer_permeability', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gplayer_Thickness', models.DecimalField(decimal_places=3, max_digits=10)),
                ('gplayer_Skin', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
