# Generated by Django 5.0.1 on 2024-02-04 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gpwellobjectives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPWellobjectivedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpwellid', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('gasrate_mmscfd', models.FloatField(blank=True, null=True)),
                ('cgr_barrels_per_mmscf', models.FloatField(blank=True, null=True)),
                ('watercut_percentage', models.FloatField(blank=True, null=True)),
                ('gpwellobjective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpwellobjectives.gpwellobjective')),
            ],
        ),
    ]
