# Generated by Django 5.0.1 on 2024-02-05 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiwellobjectives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WIWellobjectivedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiwellid', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('wat_inj_rate', models.FloatField(blank=True, null=True)),
                ('wat_inj_pressure', models.FloatField(blank=True, null=True)),
                ('tds_ppm', models.FloatField(blank=True, null=True)),
                ('pH', models.FloatField(blank=True, null=True)),
                ('wat_source', models.CharField(choices=[('Treated_Produced_Water', 'Treated_Produced_Water'), ('Treated_Sea_Water', 'Treated_Sea_Water'), ('Treated_River_Water', 'Treated_River_Water'), ('Treated_Ground_Water', 'Treated_Ground_Water')], default='1', max_length=50)),
                ('wiwellobjective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiwellobjectives.wiwellobjective')),
            ],
        ),
    ]
