# Generated by Django 4.2.1 on 2023-05-09 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sublayers', '0003_alter_sublayer_area_alter_sublayer_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifferentialLiberationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgId', models.PositiveIntegerField()),
                ('wellName', models.CharField(max_length=100)),
                ('sampleId', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('residual_oil_gravity', models.FloatField()),
                ('residual_oil_density', models.FloatField()),
                ('subLayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sublayers.sublayer')),
            ],
        ),
    ]
