# Generated by Django 5.0.1 on 2024-02-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GIRigless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifgid', models.PositiveIntegerField()),
                ('giwellid', models.PositiveIntegerField()),
                ('giunitname', models.CharField(max_length=50)),
                ('gistart_Date', models.DateField()),
                ('giend_Date', models.DateField()),
                ('giexpected_liquid', models.FloatField()),
                ('giexpected_WC', models.FloatField()),
                ('giexpected_GOR', models.FloatField()),
                ('gipre_rigless_liquid', models.FloatField()),
                ('gipre_rigless_WC', models.FloatField()),
                ('gipre_rigless_GOR', models.FloatField()),
                ('gipost_rigless_liquid', models.FloatField()),
                ('gipost_rigless_WC', models.FloatField()),
                ('gipost_rigless_GOR', models.FloatField()),
                ('gijobsummary', models.TextField(max_length=1000)),
            ],
        ),
    ]
