# Generated by Django 4.0.5 on 2022-07-03 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasingGradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casingGrade', models.CharField(max_length=20)),
                ('collapsePressure', models.DecimalField(decimal_places=3, max_digits=10)),
                ('burstPressure', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CasingSizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casingSize', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CasingWeightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casingWeight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('casingID', models.DecimalField(decimal_places=3, max_digits=10)),
                ('casingsize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casings.casingsizemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CasingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('casingType', models.CharField(choices=[('Surface', 'Surface'), ('Conductor', 'Conductor'), ('Internediate_1', 'Internediate1'), ('Intermediate_2', 'Intermediate2'), ('Intermediate_3', 'Intermediate2'), ('Liner_casing', 'Linercasing'), ('Production_Casing', 'ProductionCasing'), ('Production_Liner', 'ProductionLiner')], default='1', max_length=20)),
                ('casingID', models.DecimalField(decimal_places=3, max_digits=10)),
                ('threadType', models.CharField(choices=[('1', 'STC'), ('2', 'LTC'), ('3', 'BTC'), ('4', 'LP'), ('5', 'EUE'), ('6', 'NUE'), ('7', 'IJ'), ('8', 'VAM'), ('9', 'NEWVAM')], default='1', max_length=20)),
                ('material', models.CharField(choices=[('1', 'Carbon_Steel'), ('2', 'CRA_9Cr'), ('3', 'CRA_13Cr'), ('4', 'Inconel')], default='1', max_length=20)),
                ('shoedepth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('floatCollar', models.DecimalField(decimal_places=3, max_digits=10)),
                ('hangerDepth', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cementTop', models.DecimalField(decimal_places=3, max_digits=10)),
                ('casingGrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casings.casinggrademodel')),
                ('casingSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casings.casingsizemodel')),
                ('casingWeight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casings.casingweightmodel')),
            ],
        ),
        migrations.AddField(
            model_name='casinggrademodel',
            name='casingWeight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casings.casingweightmodel'),
        ),
    ]
