# Generated by Django 4.0.5 on 2022-07-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casings', '0002_alter_casingweightmodel_casingweight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casingweightmodel',
            name='casingID',
        ),
    ]
