# Generated by Django 4.0.5 on 2022-07-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casings', '0003_remove_casingweightmodel_casingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='casingmodel',
            name='burstPressure',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casingmodel',
            name='collapsePressure',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casingweightmodel',
            name='casingID',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
