# Generated by Django 4.0.5 on 2022-07-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casings', '0004_casingmodel_burstpressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casingmodel',
            name='burstPressure',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casingmodel',
            name='casingID',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casingmodel',
            name='collapsePressure',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
