# Generated by Django 4.0.5 on 2022-07-06 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casings', '0005_alter_casingmodel_burstpressure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casingweightmodel',
            old_name='casingsize',
            new_name='casingSize',
        ),
    ]
