# Generated by Django 4.0.5 on 2022-07-06 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casings', '0006_rename_casingsize_casingweightmodel_casingsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casingmodel',
            name='casingGrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casingGrades', to='casings.casinggrademodel'),
        ),
        migrations.AlterField(
            model_name='casingmodel',
            name='casingSize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casingSizes', to='casings.casingsizemodel'),
        ),
        migrations.AlterField(
            model_name='casingmodel',
            name='casingWeight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casingWeights', to='casings.casingweightmodel'),
        ),
    ]
