# Generated by Django 4.1.4 on 2023-02-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casings", "0007_alter_casingmodel_casinggrade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casingmodel",
            name="casingType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Surface", "Surface"),
                    ("Conductor", "Conductor"),
                    ("Internediate_1", "Internediate1"),
                    ("Intermediate_2", "Intermediate2"),
                    ("Intermediate_3", "Intermediate2"),
                    ("Liner_casing", "Linercasing"),
                    ("Production_Casing", "ProductionCasing"),
                    ("Production_Liner", "ProductionLiner"),
                ],
                default="Surface",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="casingmodel",
            name="cementTop",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="casingmodel",
            name="floatCollar",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="casingmodel",
            name="hangerDepth",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="casingmodel",
            name="material",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Carbon_Steel"),
                    ("2", "CRA_9Cr"),
                    ("3", "CRA_13Cr"),
                    ("4", "Inconel"),
                ],
                default="1",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="casingmodel",
            name="shoedepth",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="casingmodel",
            name="threadType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "STC"),
                    ("2", "LTC"),
                    ("3", "BTC"),
                    ("4", "LP"),
                    ("5", "EUE"),
                    ("6", "NUE"),
                    ("7", "IJ"),
                    ("8", "VAM"),
                    ("9", "NEWVAM"),
                ],
                default="1",
                max_length=20,
                null=True,
            ),
        ),
    ]
