# Generated by Django 5.0.1 on 2024-03-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casings', '0008_alter_casingmodel_casingtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casingmodel',
            name='burstPressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingmodel',
            name='casingID',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingmodel',
            name='cementTop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingmodel',
            name='collapsePressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingmodel',
            name='floatCollar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingmodel',
            name='hangerDepth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casingmodel',
            name='shoedepth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
