# Generated by Django 5.0.1 on 2024-03-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casings', '0009_alter_casingmodel_burstpressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casingsizemodel',
            name='casingSize',
            field=models.CharField(max_length=10),
        ),
    ]
