# Generated by Django 5.0.1 on 2024-02-09 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wicasings', '0001_initial'),
        ('wileakoffTests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WILeakoffTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witime', models.FloatField()),
                ('wivolume', models.FloatField()),
                ('wipressure', models.FloatField()),
                ('wicasingSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wicasings.wicasingsizemodel')),
                ('wileakoffTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wileakoffTests.wileakofftest')),
            ],
        ),
    ]
