# Generated by Django 5.0.1 on 2024-02-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GIFishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giwellid', models.PositiveBigIntegerField()),
                ('gifgid', models.PositiveBigIntegerField()),
                ('gifish_Date', models.DateTimeField()),
                ('gifish_Top', models.FloatField()),
                ('gifish_Bottom', models.FloatField()),
                ('gifish_Nature', models.CharField(blank=True, max_length=50, null=True)),
                ('gifish_Description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
