# Generated by Django 5.0.1 on 2024-02-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GITestResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifgId', models.PositiveIntegerField()),
                ('giwellid', models.PositiveIntegerField()),
                ('giformation', models.CharField(max_length=100)),
                ('gitop_MD', models.FloatField()),
                ('gibottom_MD', models.FloatField()),
                ('gitest_Duration', models.FloatField()),
                ('gichoke_Size', models.CharField(max_length=100)),
                ('githp', models.FloatField()),
                ('gibhp', models.FloatField()),
                ('giliquid_Rate', models.FloatField()),
                ('gioil_Rate', models.FloatField()),
                ('gigas_Rate', models.FloatField()),
                ('giwater_Cut', models.FloatField()),
                ('giremarks', models.CharField(max_length=100)),
            ],
        ),
    ]
