# Generated by Django 4.2.1 on 2023-06-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressuredropCalculationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fgid', models.PositiveIntegerField()),
                ('wellid', models.PositiveIntegerField()),
                ('model_Date', models.DateField()),
                ('source_Pressure', models.FloatField()),
                ('source_Flowrate', models.FloatField()),
                ('source_Temp', models.FloatField()),
                ('pipe_Angle', models.FloatField()),
                ('pipe_Length', models.FloatField()),
                ('pipe_Diam', models.FloatField()),
                ('fluid_API', models.FloatField()),
                ('fluid_WaterCut', models.FloatField()),
                ('fluid_GOR', models.FloatField()),
                ('fluid_gas_spgr', models.FloatField()),
            ],
        ),
    ]
