# Generated by Django 5.0.1 on 2024-02-16 11:33

import django.db.models.deletion
import gppressurebuildupanalysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blackoilpvt', '0019_alter_blackoilpvt_gasgravity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPPressureBuildupDataUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpsurvey_Date', models.DateField()),
                ('gptime', models.TimeField()),
                ('gpelapsedtime', models.FloatField()),
                ('gpgauge_pressure', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GPPressureBuildupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgid', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpsurvey_Date', models.DateField()),
                ('gpgauge_Depth', models.FloatField()),
                ('gplayer_Thickness', models.FloatField()),
                ('gplayer_Porosity', models.FloatField()),
                ('gptotal_Compressibility', models.FloatField()),
                ('gpmu_oil', models.FloatField()),
                ('gpoil_FVF', models.FloatField()),
                ('gpwellbore_Radius', models.FloatField()),
                ('gpoil_Prod_Rate', models.FloatField()),
                ('gpwater_Cut', models.FloatField()),
                ('gpt_since_shutin', models.FloatField()),
                ('gptest_Type', models.CharField(blank=True, choices=[('Constant_Rate', 'Constant_Rate'), ('Constant_Pressure', 'Constant_Pressure'), ('Multi_Rate', 'Multi_Rate')], default='Constant_Rate', max_length=50, null=True)),
                ('gpguess_Value', models.PositiveBigIntegerField(default=10)),
                ('gpdataFile', models.FileField(blank=True, null=True, upload_to=gppressurebuildupanalysis.models.filepath)),
                ('gppvt_Well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blackoilpvt.blackoilpvt')),
            ],
        ),
    ]
