# Generated by Django 5.0.1 on 2024-02-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPGradientSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgId', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpsurvey_Date', models.DateField()),
                ('gpsurvey_Type', models.CharField(choices=[('Flogpng', 'Flogpng'), ('Static', 'Static')], default='Static', max_length=50)),
                ('gpshutin_Period', models.FloatField()),
                ('gptubinghead_Pressure', models.FloatField()),
                ('gptubinghead_Temperature', models.FloatField()),
                ('gpliquid_Rate', models.FloatField()),
                ('gpwater_Cut', models.FloatField()),
                ('gpgas_Oil_Ratio', models.FloatField()),
            ],
        ),
    ]
