# Generated by Django 5.0.1 on 2024-02-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPOilShowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgId', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpformation', models.CharField(max_length=100)),
                ('gptop_MD', models.FloatField()),
                ('gpbottom_MD', models.FloatField()),
                ('gpsample_Type', models.CharField(max_length=100)),
                ('gpsample_Description', models.CharField(max_length=500)),
                ('gpremarks', models.CharField(max_length=100)),
            ],
        ),
    ]
