# Generated by Django 4.1.4 on 2023-01-30 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coiltubing", "0002_alter_coiltubing_ctname_coiltubingoperation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CoiltubingOperation",
        ),
    ]
