# Generated by Django 4.2.1 on 2023-06-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espdesign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espdesignmodel',
            name='fgId',
        ),
        migrations.AddField(
            model_name='espdesignmodel',
            name='water_Salinity',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='espdesignmodel',
            name='gas_Separator_Efficiency',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='espdesignmodel',
            name='fgid',
            field=models.PositiveIntegerField(default=15000),
            preserve_default=False,
        ),
    ]
