# Generated by Django 4.2.1 on 2023-06-28 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackoilpvt', '0019_alter_blackoilpvt_gasgravity_and_more'),
        ('espdesign', '0002_remove_espdesignmodel_fgid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='espdesignmodel',
            name='pvt_Well',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blackoilpvt.blackoilpvt'),
        ),
    ]
