# Generated by Django 4.2.1 on 2023-07-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espdesign', '0004_espdesignmodel_pump_depth_espdesignmodel_water_spgr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espdesignmodel',
            name='pump',
            field=models.CharField(choices=[('400-D800N-60Hz-250-1150bpd', '400-D800N-60Hz-250-1150bpd'), ('400-D1100-60Hz-400-1650bpd-154Hp', '400-D1100-60Hz-400-1650bpd-154Hp'), ('400-D1050-60Hz-300-1650bpd-154Hp', '400-D1050-60Hz-300-1650bpd-154Hp'), ('400-D1750-60Hz-300-1650bpd-154Hp', '400-D1750-60Hz-1200-2050bpd-125Hp')], default='400-D1050-60Hz-300-1650bpd-154Hp', max_length=100),
        ),
    ]
