# Generated by Django 5.0.1 on 2024-02-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBDeviationsurveydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obfgId', models.PositiveIntegerField()),
                ('obwellid', models.PositiveIntegerField()),
                ('obmeasuredDepth', models.FloatField()),
                ('obangle', models.FloatField()),
                ('obazimuth', models.FloatField()),
                ('obtvd', models.FloatField(blank=True, null=True)),
                ('obnorthSouth', models.FloatField(blank=True, null=True)),
                ('obeastWest', models.FloatField(blank=True, null=True)),
                ('obnetDrift', models.FloatField(blank=True, null=True)),
                ('obnetDirection', models.FloatField(blank=True, null=True)),
                ('obverticalSection', models.FloatField(blank=True, null=True)),
                ('obdogLeg', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
