# Generated by Django 5.0.1 on 2024-02-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obcasings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OBLeakoffTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obfgid', models.PositiveIntegerField()),
                ('obwellid', models.PositiveIntegerField()),
                ('obanalyst', models.CharField(max_length=30)),
                ('obrecorded_Date', models.DateField()),
                ('obmudWeight', models.FloatField()),
                ('obopenholeLength', models.FloatField()),
                ('obcasingSize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obcasings.obcasingsizemodel')),
            ],
        ),
    ]
