# Generated by Django 5.0.1 on 2024-02-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPWellobjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpwellname', models.CharField(max_length=50)),
                ('gpfgid', models.PositiveIntegerField()),
                ('gpobjectives', models.TextField(max_length=2000)),
            ],
        ),
    ]
