# Generated by Django 5.0.1 on 2024-02-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPDrillingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgId', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpstart_Date', models.DateField()),
                ('gpend_Date', models.DateField()),
                ('gpliquid_Rate', models.FloatField()),
                ('gpwater_Cut', models.FloatField()),
                ('gpgas_Rate', models.FloatField()),
                ('gpoil_Rate', models.FloatField()),
                ('gpgas_Oil_Ratio', models.FloatField()),
                ('gpdrilling_Summary', models.TextField(max_length=2000)),
            ],
        ),
    ]
