# Generated by Django 5.0.1 on 2024-02-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBCementPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obwellid', models.PositiveBigIntegerField()),
                ('obfgid', models.PositiveBigIntegerField()),
                ('obplug_Date', models.DateField()),
                ('obplug_Top', models.FloatField()),
                ('obplug_Bottom', models.FloatField()),
                ('obcement_Density', models.FloatField()),
                ('obcement_Volume', models.FloatField()),
                ('obplug_Description', models.TextField(blank=True, max_length=2500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OBPumpingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obwellid', models.PositiveBigIntegerField()),
                ('obfgid', models.PositiveBigIntegerField()),
                ('obpump_Time', models.TimeField()),
                ('obpump_Fluid', models.CharField(blank=True, choices=[('Pre_Flush', 'Pre_Flush'), ('Slurry', 'Slurry'), ('Post_Flush', 'Post_Flush'), ('Water', 'Water')], default='Pre_Flush', max_length=20, null=True)),
                ('obpump_Fluid_Density', models.FloatField()),
                ('obpump_Pressure', models.FloatField()),
                ('obpump_Rate', models.FloatField()),
                ('obcementplug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obcementplugs.obcementplug')),
            ],
        ),
    ]
