# Generated by Django 4.2.1 on 2023-05-27 00:27

from django.db import migrations, models
import loganalysis.models


class Migration(migrations.Migration):

    dependencies = [
        ('loganalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loganalysismodel',
            name='file_Name',
            field=models.FileField(blank=True, null=True, upload_to=loganalysis.models.filepath),
        ),
        migrations.AddField(
            model_name='loganalysismodel',
            name='file_type',
            field=models.CharField(choices=[('LAS', 'LAS'), ('CSV', 'CSV'), ('DLIS', 'DLIS')], default='LAS', max_length=50),
        ),
    ]
