# Generated by Django 4.1.4 on 2023-02-18 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drillingsummary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrillingOps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fgId", models.PositiveIntegerField()),
                ("wellid", models.PositiveIntegerField()),
                ("ops_Date", models.DateField()),
                ("time_From", models.TimeField()),
                ("time_To", models.TimeField()),
                ("totalhrs", models.FloatField()),
                (
                    "ops_Code",
                    models.CharField(
                        choices=[
                            ("BOPTest", "BOPTest"),
                            ("CasingRun", "CasingRun"),
                            ("Cementing", "Cementing"),
                            ("CementSqueeze", "CementSqueeze"),
                            ("Circulation", "Circulation"),
                            ("CoilTubing", "CoilTubing"),
                            ("Conditioning", "Conditioning"),
                            ("Coring", "Coring"),
                            ("DeviationSurvey", "DeviationSurvey"),
                            ("Drilling", "Drilling"),
                            ("DrillStemTest", "DrillStemTest"),
                            ("Fishing", "Fishing"),
                            ("NonProductive", "NonProductive"),
                            ("OperatingStatus", "OperatingStatus"),
                            ("Others", "Others"),
                            ("Perforating", "Perforating"),
                            ("PlugBack", "PlugBack"),
                            ("Reaming", "Reaming"),
                            ("RigDownBOP", "RigDownBOP"),
                            ("RigMove", "RigMove"),
                            ("Rigup", "Rigup"),
                            ("RigMaintenance", "RigMaintenance"),
                            ("RigRepair", "RigRepair"),
                            ("RigUpBOP", "RigUpBOP"),
                            ("ReplaceDrillingLine", "ReplaceDrillingLine"),
                            ("TearDown", "TearDown"),
                            ("TripIn", "TripIn"),
                            ("TripOut", "TripOut"),
                            ("WaitOnCement", "WaitOnCement"),
                            ("WaitOnWeather", "WaitOnWeather"),
                            ("WirelineLogs", "WirelineLogs"),
                            ("RunRiserEquipment", "RunRiserEquipment"),
                            ("RetrieveRiserEquipment", "RetrieveRiserEquipment"),
                            ("Safety", "Safety"),
                            ("SubSeaInstallation", "SubSeaInstallation"),
                            ("SurfaceTesting", "SurfaceTesting"),
                            ("Swabbing", "Swabbing"),
                            ("Testing", "Testing"),
                            ("Treating", "Treating"),
                            ("TubingTrip", "TubingTrip"),
                            ("WellCompletion", "WellCompletion"),
                            ("WellControl", "WellControl"),
                        ],
                        default="Drilling",
                        max_length=50,
                    ),
                ),
                ("ops_Summary", models.TextField(max_length=2000)),
                (
                    "drillingid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drillingsummary.drillingsummary",
                    ),
                ),
            ],
        ),
    ]
