# Generated by Django 5.0.1 on 2024-02-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPFishModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpwellid', models.PositiveBigIntegerField()),
                ('gpfgid', models.PositiveBigIntegerField()),
                ('gpfish_Date', models.DateTimeField()),
                ('gpfish_Top', models.FloatField()),
                ('gpfish_Bottom', models.FloatField()),
                ('gpfish_Nature', models.CharField(blank=True, max_length=50, null=True)),
                ('gpfish_Description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
