# Generated by Django 5.0.1 on 2024-02-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WIGasShowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifgId', models.PositiveIntegerField()),
                ('wiwellid', models.PositiveIntegerField()),
                ('wiformation', models.CharField(max_length=100)),
                ('witop_MD', models.FloatField()),
                ('wibottom_MD', models.FloatField()),
                ('witotal_Gas', models.FloatField()),
                ('wimethane', models.FloatField()),
                ('wiethane', models.FloatField()),
                ('wipropane', models.FloatField()),
                ('wiiso_Butane', models.FloatField()),
                ('wineo_Butane', models.FloatField()),
                ('wiiso_Pentane', models.FloatField()),
                ('wineo_Pentane', models.FloatField()),
                ('wiremarks', models.CharField(max_length=100)),
            ],
        ),
    ]
