# Generated by Django 5.0.1 on 2024-02-09 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gicasings', '0001_initial'),
        ('gileakoffTests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GILeakoffTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitime', models.FloatField()),
                ('givolume', models.FloatField()),
                ('gipressure', models.FloatField()),
                ('gicasingSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gicasings.gicasingsizemodel')),
                ('gileakoffTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gileakoffTests.gileakofftest')),
            ],
        ),
    ]
