# Generated by Django 5.0.1 on 2024-02-16 11:33

import gpconstantpressuredrawdowntestanalysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPConstantPressureDrawdowntest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgid', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpsurvey_Date', models.DateField()),
                ('gpgauge_Depth', models.FloatField()),
                ('gplayer_Porosity', models.FloatField()),
                ('gplayer_Thickness', models.FloatField()),
                ('gpwellbore_Radius', models.FloatField()),
                ('gptotal_Compressibility', models.FloatField()),
                ('gpinitial_Res_Pres', models.FloatField()),
                ('gpoil_Viscosity', models.FloatField()),
                ('gpoil_FVF', models.FloatField()),
                ('gppwf', models.FloatField()),
                ('gpfile_Name', models.FileField(blank=True, null=True, upload_to=gpconstantpressuredrawdowntestanalysis.models.filepath)),
            ],
        ),
    ]
