# Generated by Django 5.0.1 on 2024-02-13 23:49

import gploganalysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPLogAnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpfgid', models.PositiveIntegerField()),
                ('gpwellid', models.PositiveIntegerField()),
                ('gpcasingSize', models.CharField(choices=[('4', '4'), ('4 1/2', '4 1/2'), ('5', '5'), ('5 1/2', '5 1/2'), ('6 5/8', '6 5/8'), ('7', '7'), ('7 5/8', '7 5/8'), ('7 3/4', '7 3/4'), ('8 5/8', '8 5/8'), ('9 5/8', '9 5/8'), ('10 3/4', '10 3/3'), ('11 3/4', '11 3/3'), ('13 3/8', '13 3/8'), ('16', '16'), ('18 5/8', '18 5/8'), ('20', '20')], default='7', max_length=50)),
                ('gpanalyst', models.CharField(max_length=30)),
                ('gprecorded_date', models.DateField()),
                ('gpinterpretation', models.TextField()),
                ('gplogImage', models.ImageField(blank=True, null=True, upload_to=gploganalysis.models.filepath)),
                ('gpremarks', models.CharField(max_length=100)),
                ('gpfile_type', models.CharField(choices=[('LAS', 'LAS'), ('CSV', 'CSV'), ('DLIS', 'DLIS')], default='LAS', max_length=50)),
                ('gpfile_Name', models.FileField(blank=True, null=True, upload_to=gploganalysis.models.filepath)),
            ],
        ),
    ]
