# Generated by Django 5.0.1 on 2024-02-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GIPerforationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifgid', models.PositiveIntegerField()),
                ('giwellid', models.PositiveIntegerField()),
                ('giperf_Date', models.DateField()),
                ('giperf_Top', models.FloatField()),
                ('giperf_Bottom', models.FloatField()),
                ('giperf_Condition', models.CharField(choices=[('Over_Balanced', 'Over_Balanced'), ('Under_balanced', 'Under_balanced')], default='Over_Balanced', max_length=50)),
                ('giconveyance_Method', models.CharField(choices=[('Through_Casing', 'Through_Casing'), ('Through_Tubing', 'Through_Tubing'), ('TCP', 'TCP')], default='Retrievable_Hallow', max_length=50)),
                ('giperf_Gun_Type', models.CharField(choices=[('Retrievable_Hallow', 'Retrievable_Hallow'), ('Expendable', 'Expendable'), ('Semi_Expendable', 'Semi_Expendable')], default='Retrievable_Hallow', max_length=50)),
                ('giperf_Gun_Size', models.CharField(choices=[('2_in', '2_in'), ('2_3/4_In', '2_3/4_in'), ('3_1/8_in', '3_1/8_in'), ('3_3/8_in', '3_3/8_in')], default='2_in', max_length=50)),
                ('giperf_Gun_Density', models.CharField(max_length=50)),
                ('giperf_Charges', models.CharField(max_length=50)),
                ('giremarks', models.CharField(max_length=100)),
            ],
        ),
    ]
