# Generated by Django 5.0.1 on 2024-02-09 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('widrillingsummary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WIDrillingProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifgId', models.PositiveIntegerField()),
                ('wiwellid', models.PositiveIntegerField()),
                ('wiops_Date', models.DateField()),
                ('wihole_Size', models.CharField(choices=[('26_inch', '26_inch'), ('20_inch', '20_inch'), ('16_inch', '16_inch'), ('12_1/4_inch', '12_1/4_inch'), ('8_1/2_inch', '8_1/2_inch'), ('6_1/8_inch', '6_1/8_inch'), ('4_1/2_inch', '4_1/2_inch')], default='12_1/4_inch', max_length=50)),
                ('widepth_From', models.FloatField()),
                ('widepth_To', models.FloatField()),
                ('widescription', models.TextField(max_length=2500)),
                ('wipossible_reason', models.TextField(max_length=2500)),
                ('widrillingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widrillingsummary.widrillingsummary')),
            ],
        ),
    ]
