# Generated by Django 3.0.14 on 2022-05-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('layers', '0001_initial'),
        ('blocks', '0001_initial'),
        ('oilfields', '0001_initial'),
        ('sublayers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FGIModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Asset')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.Block')),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.Layer')),
                ('oilfield', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oilfields.Oilfield')),
                ('sublayer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sublayers.Sublayer')),
            ],
        ),
    ]
