# Generated by Django 3.0.14 on 2022-05-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fgimodel',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='is_selected'),
        ),
    ]
