# Generated by Django 3.0.14 on 2022-05-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgis', '0002_fgimodel_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgimodel',
            name='is_selected',
            field=models.BooleanField(),
        ),
    ]
